aztfmod/terraform-azurerm-caf

azure_machine_learning.tf, main.tf, modules/analytics/azure_machine_learning/main.tf, modules/analytics/azure_machine_learning/output.tf, modules/analytics/azure_machine_learning/variables.tf, modules/analytics/azure_machine_learning/workspace.tf, readme.md, solutions/examples/data_analytics/200-basic-ml/aml_configuration.tfvars
Azure ML workspace module added
=> Azure ML workspace module added

modules/networking/private-dns/module.tf
added prefix by azurecaf breaking the dns resolve
=> Comment out azurecaf for private dns

.github/workflows/master-100.yaml, app_service_environments.tf, app_service_plans.tf, app_services.tf, examples/main.tf, local.combined_objects.tf, modules/app_insights/output.tf, modules/webapps/appservice/main.tf, modules/webapps/appservice/slot.tf, modules/webapps/appservice/variables.tf
add ase to local combine object to isolate asp
=> add ase to combine object for asp isolation

examples/mssql_server/elastic_pools/configuration.tfvars, examples/synapse_analytics/100-synapse/configuration.tfvars, examples/synapse_analytics/101-synapse-sparkpool/configuration.tfvars, modules/databases/mssql_server/private_endpoints.tf, modules/databases/mssql_server/server.tf, modules/databases/mssql_server/variables.tf, modules/security/keyvault_access_policies/policies.tf, mssql_servers.tf
msssql & synanpse example fix
remove checking on var for ad, group and msi on access poilicies
=> fix broken examples

keyvault.tf, modules/security/keyvault_access_policies/policies.tf, variables.tf
Create new variable for azure ad app key vault policies assignment to avoid conflict with other resources policies assignment
=> Ak kv access policies

modules/security/dynamic_keyvault_secrets/keyvault.tf, modules/security/dynamic_keyvault_secrets/secret/keyvault_secret.tf, modules/security/dynamic_keyvault_secrets/secret/variables.tf, modules/security/dynamic_keyvault_secrets/secret_immutable/keyvault_secret.tf, modules/security/dynamic_keyvault_secrets/secret_immutable/variables.tf, modules/security/dynamic_keyvault_secrets/variables.tf
```hcl
dynamic_keyvault_secrets = {
applications = {                            # Key of the keyvault to store the secrets
application_demo_app1 = {                 # Dynamic secret key. Can be modifed as needed.
output_key    = "managed_identities"    # Name of the output variable name
resource_key  = "application_demo_app1" # Name of the resource
attribute_key = "id"                    # Attribute to store in the keyvault secret
secret_name   = "application-demo-app1" # Name of the secret
}
application_demo_app2 = {                 # Dynamic secret key. Can be modifed as needed.
output_key    = "managed_identities"    # Name of the output variable name
resource_key  = "application_demo_app2" # Name of the resource
attribute_key = "id"                    # Attribute to store in the …
```
=> Add private module dynamic secrets

modules/networking/application_gateway/locals.networking.tf, modules/networking/routes/module.tf, modules/networking/routes/variables.tf, networking.tf
Added support on 3rd part NVA to route in route table
=> 0.4 route nva

modules/analytics/machine_learning/compute_instance.tf, modules/analytics/machine_learning/compute_instance/arm_compute_instance.json, modules/analytics/machine_learning/compute_instance/locals.arm_parameters.tf, modules/analytics/machine_learning/compute_instance/main.tf, modules/analytics/machine_learning/compute_instance/variables.tf
Refactoring ARM template to add naming convention to compute and adding tags to compute.
=> Azure Machine Learning Compute name collision and tags missing

.github/workflows/master-100.yaml, .github/workflows/master-200.yaml, examples/mssql_server/elastic_pools/configuration.tfvars, locals.combined_objects.tf, mssql_databases.tf
add elastic pools as combine object
#113
=> Expose elastic pool as remote object

modules/databases/mssql_elastic_pool/elastic_pool.tf, mssql_databases.tf, mssql_elastic_pools.tf
- update elastic pool config capacity to be mandatory field 
- update mssql database can be created without elastic pool
=> Rc elasticpool bug

networking.tf, virtual_machines.tf
Quick fix for ```use_slug``` regression in 0.4.16 for networking.tf
=> Patch - networking slug

bastion_service.tf, modules/security/keyvault/keyvault.tf
Added timeout to 60 minutes to Bastion Host:
```
timeouts {
create = "60m"
} 
```
=> Fixing Timeout errors

.github/workflows/master-100.yaml, examples/compute/kubernetes_services/101-single-cluster/aks.tfvars, examples/compute/kubernetes_services/101-single-cluster/networking.tfvars, examples/main.tf, main.tf
In order to have clearer error message on module version misalignment between LZ and module.
=> Add minimum provider version constraint

examples/networking/front_door/100-simple-front_door/dns_zone.tfvars, roles.tf
added roles from local combined objects for role mapping.
=> akloth roles

modules/compute/wvd_application_group/output.tf, modules/compute/wvd_application_group/virtual_desktop_application_group.tf, modules/compute/wvd_host_pool/virtual_desktop_host_pool.tf, modules/compute/wvd_workspace/output.tf, modules/compute/wvd_workspace/virtual_desktop_workspace.tf
formatting cleanup and added placeholder comments pending azurecaf naming support
=> naming cleanup and comments

.devcontainer/docker-compose.yml, .github/workflows/master-100.yaml, .github/workflows/master-sql-mi.yaml, .github/workflows/master-standalone.yaml
January 2021 Stable rover update
=> Update release aztfmod/rover:2101.2813

application_gateways.tf, modules/compute/aks/README.md, modules/compute/aks/aks.tf
Bug fix for certificate request to complete before application gateway.
=> Adding dependency on cert requests for App Gateways

modules/databases/mssql_server/server.tf
missing property in mssql_server - minimum_tls_version
=> add minimum_tls_version to sql server

examples/networking/virtual_network_gateway/101-vpn-site-to-site/configuration.tfvars, modules/networking/local_network_gateways/module.tf, modules/networking/virtual_network_gateways/module.tf
To fix : https://github.com/aztfmod/terraform-azurerm-caf/issues/256
Updated example files and tested.
=> Fix BGP Settings in  Virtual Network Gateway and Local Network Gateway modules

modules/databases/mssql_database/database.tf
=> #258 Added support for mssql_database.storage_account_type

modules/databases/mssql_database/database.tf
Integration of #258 Added support for mssql_database.storage_account_type from integration for CI checks.
=> Added support for mssql_database.storage_account_type #258 

examples/main.tf
=> bump azurecaf version

modules/azuread/applications/keyvault_secrets.tf, modules/azuread/applications/module.tf
during upgrade
This is to provide a smooth migration to password rotation
=> update aad apps password key to prevent cycle error

modules/networking/virtual_network/module.tf
changing **dns** to **dns_servers** in vnet module to make it the same in the provider
=> changing dns to dns_servers in vnet module

.github/workflows/master-sql-mi-tf13.yaml, .github/workflows/master-sql-mi-tf14.yaml, .github/workflows/master-sql-mi-tf15.yaml, examples/app_gateway/210-agw-with-keyvault/application.tfvars, landingzones/caf_example/module.tf, landingzones/caf_example/variables.tf, modules/networking/application_gateway/application_gateway.tf, msssql_managed_databases.tf
Support manual cert in AGW. Resolves #352  
Fix SQL MI remote LZ bugs #355
=> Add cert name support for AGW and Fix remote LZ bugs in SQL MI for location and base tags

examples/networking/load_balancers/101-load-balancer-with-rules/configuration.tfvars, load_balancers.tf, modules/networking/load_balancers/load_balancers.tf, modules/networking/load_balancers/output.tf
- Refactored the Load balancer Probe Block to support multiple probes.
- Added Backend Pool Output attributes
=> Load Balancer module enhancements

modules/compute/virtual_machine/vm_disk.tf
Submitting the PR on behalf of @anamikanayal01 @manojtjacob
=> Refactor disk encryption argument

modules/azuread/applications/module.tf
=> Fix regression issue for azure ad app naming and cycle issue

diagnostics.tf, examples/storage_accounts/100-simple-storage-account-blob-container/configuration.tfvars, examples/storage_accounts/100-simple-storage-account-blob-container/keyvaults.tfvars, keyvault.tf, locals.combined_objects.tf, modules/security/keyvault_access_policies/policies.tf
Updated the diagnostics module
Updated the changes in storage_accounts/100-simple-storage-account-blob-container
=> Adding code for cmk encryption - diagnostic storage account

modules/azuread/applications/module.tf, modules/azuread/groups/group.tf, modules/azuread/groups_members/members.tf
Reverting azuread_group (1.4.0) name to display_name
=> Revert to display_name for AAD provider

modules/compute/virtual_machine/vm_windows.tf
Fixed the des_id for windows vm
=> Refactor disk encryption set argument - Windows VM

modules/networking/load_balancers/load_balancers.tf
To fix : https://github.com/aztfmod/terraform-azurerm-caf/issues/389
=> Add explicit dependancy for lb_probe

examples/storage_accounts/103-storage-account-network-rules/configuration.tfvars, modules/storage_account/storage_account.tf
to fix https://github.com/aztfmod/terraform-azurerm-caf/issues/419
=> Fix ip_rules and bypass arguments for storage accounts

examples/compute/virtual_machine/100-single-linux-vm/configuration.tfvars, modules/compute/virtual_machine/network_interface.tf
=> VM: Adding external network objects reference by ID

.github/workflows/master-100-testcases.json, .github/workflows/master-standalone-tf13.yaml, .github/workflows/master-standalone-tf14.yaml, .github/workflows/master-standalone-tf15.yaml, examples/redis_cache/102-redis-private/README.md, examples/redis_cache/102-redis-private/configuration.tfvars, modules/redis_cache/module.tf, modules/redis_cache/variables.tf, redis_caches.tf
=> Add support for Redis Cache VNET integration

modules/compute/aks/aks.tf
=> Fix aks node pool subnet

.github/workflows/master-100-testcases.json, .github/workflows/master-standalone-tf13.yaml, .github/workflows/master-standalone-tf14.yaml, .github/workflows/master-standalone-tf15.yaml, examples/webapps/function_app/101-function_app-private/configuration.tfvars, function_app.tf, modules/webapps/function_app/module.tf, modules/webapps/function_app/variables.tf
=> Add support for Function App VNET integration

app_services.tf, examples/webapps/appservice/107-appservice-private/configuration.tfvars
Fixes submap path for #427 
* During refactor one of the keys was missed
* Includes also suggested new submap for these settings
* Example has been adapted accordingly
=> Fix submap for Appservice VNET integration

modules/networking/network_security_group/module.tf
To fix https://github.com/aztfmod/terraform-azurerm-caf/issues/441
=> Fix naming issue for NSGs

examples/storage_accounts/102-storage-account-advanced-options/configuration.tfvars, examples/storage_accounts/102-storage-account-advanced-options/standalone/module.tf, examples/storage_accounts/102-storage-account-advanced-options/standalone/variables.tf, locals.tf, modules/security/management_locks/main.tf, modules/security/management_locks/management_lock.tf, modules/security/management_locks/variables.tf, variables.tf
Updated the Management Lock code
=> Updated the MangementLock Code

examples/compute/availability_set/100-simple-availabilityset/configuration.tfvars, examples/compute/availability_set/101-availabilityset-with-proximity-placement-group/configuration.tfvars, examples/compute/virtual_machine/100-single-linux-vm/configuration.tfvars, examples/compute/virtual_machine/101-single-windows-vm/configuration.tfvars, examples/compute/virtual_machine/104-single-windows-backup/configuration.tfvars, examples/compute/virtual_machine/105-single-windows-vm-kv-admin-secrets/configuration.tfvars, examples/compute/virtual_machine/210-vm-bastion-winrm/virtual_machines.tfvars, examples/compute/virtual_machine/211-vm-bastion-winrm-agents/virtual_machines.tfvars, modules/compute/virtual_machine/variables.tf, modules/compute/virtual_machine/vm_linux.tf, modules/compute/virtual_machine/vm_windows.tf, virtual_machines.tf
=> Integration - Add support for managed boot diagnostics on VMs, etc. #368

examples/networking/load_balancers/101-load-balancer-with-rules/configuration.tfvars, modules/networking/load_balancers/load_balancers.tf
Fixed the probe_id argument in the load balancer rules resources. Updated example configs as well.
=> Fix Load Balancer rule

modules/networking/virtual_network/module.tf, modules/networking/virtual_network/nsg/diagnostics.tf, modules/networking/virtual_network/nsg/module.tf, modules/networking/virtual_network/nsg/nsg_flow_logs.tf, modules/networking/virtual_network/nsg/variables.tf, modules/networking/virtual_network/variables.tf, network_security_groups.tf, networking.tf
- Have updated the Virtual Network module code.
- Have tested the following scenarios
1. The NSGs are not duplicated during deployments.
2. Version 1 NSGs can be created to the specified Resource Groups. 
3. Version 1 NSGs can be attached to NIC or subnets.
=> Updating the NSG code - Fixed the NSG duplication issue for Version 1 NSGs

modules/networking/application_gateway/application_gateway.tf, modules/networking/application_gateway/locals.backend_pools.tf
Null check for app gateway, the fqdns are optional so null check require.
=> null check added for fqdn

modules/azuread/applications/scripts/grant_consent.sh
This script is missing  `/` within the path which is causing failures. 
Bug: https://github.com/aztfmod/terraform-azurerm-caf/issues/499
=> [BUG] Script is missing a "/" in path

.github/workflows/standalone-scenarios.json, examples/eventhub/102-namespace-and-evh-with-auth-rules/configuration.tfvars, examples/eventhub/104-namespace-and-evh-with-storage/configuration.tfvars, modules/event_hubs/consumer_groups/consumer_groups.tf, modules/event_hubs/consumer_groups/output.tf, modules/event_hubs/consumer_groups/variables.tf, modules/event_hubs/hubs/auth_rules/auth_rules.tf, modules/event_hubs/hubs/event_hub.tf, modules/event_hubs/hubs/output.tf, modules/event_hubs/hubs/variables.tf
General review and settings refresh up to azurerm 2.64.0
=> Review Event Hub logic and configurations

application_gateways.tf, examples/compute/virtual_machine/106-marketplace-image-with-plan/configuration.tfvars, examples/compute/virtual_machine_scale_set/100-linux-win-vmss-lb/configuration.tfvars, examples/compute/virtual_machine_scale_set/101-linux-win-vmss-agw/configuration.tfvars, keyvault.tf, keyvault_certificate_issuers.tf, load_balancers.tf, networking.tf, virtual_machines.tf, virtual_machines_scale_sets.tf
Reverts aztfmod/terraform-azurerm-caf#542
=> Revert "Feature/remote rg selected resources"

application_gateways.tf, keyvault.tf, load_balancers.tf, modules/networking/application_gateway/locals.networking.tf, modules/security/keyvault/keyvault.tf, modules/security/keyvault/private_endpoints.tf, networking.tf, virtual_machines.tf
Update remote rg structure for :
- KV
- AGW
- ALB
- Vnet
- Route table, routes
- network watcher
- VM
=> Update remote RG structure for selected modules

.github/workflows/standalone-scenarios.json, examples/netapp/102-nfs-export-policy/configuration.tfvars
This PR resolves integration issue in 101-nfs example where NFSv3 volumes were being created however export policy was set to NFSv4.1. #517 
Integration test file has also been updated.
=> NFS Export Policy

modules/networking/application_gateway/application_gateway.tf
This PR adds WAF configuration support to application gateway.
Raised in issue #377 
Example
```hcl
waf_configuration = {
enabled = true
firewall_mode = "Prevention"
rule_set_type = "OWASP"
rule_set_version = "3.1"
disabled_rule_groups = {
rule1 = {
rule_group_name = "General"
rules = ["911100"]
}
}
exclusions = {
exc1 = {
match_variable = "RequestHeaderNames"
selector_match_operator = "Equals"
selector = "SomeHeader"
}
}
}
=> added support for specifying application gateway WAF config

modules/networking/application_gateway/application_gateway.tf
Addresses part 1 of issue #557
=> added support for specifying host name on backend http settings

event_hubs.tf
Fix for the issue creating event hub with private link issue #583
=> Fix event hub private link issue 583

modules/networking/application_gateway/application_gateway.tf
This PR addresses issue #586. I took the minimalistic approach for now.
=> fixed resolving of backend address pool name for application gateway path rule

examples/networking/virtual_network/202-nsg-flow-logs-v2/configuration.tfvars, examples/networking/virtual_network/202-nsg-flow-logs-v2/diagnostics_definitions.tfvars, examples/networking/virtual_network/202-nsg-flow-logs-v2/diagnostics_destinations.tfvars, examples/networking/virtual_network/202-nsg-flow-logs-v2/nsg_definitions.tfvars, modules/networking/network_security_group/nsg_flow_logs.tf, modules/networking/network_security_group/variables.tf, modules/networking/network_watcher/output.tf, modules/networking/virtual_network/module.tf, modules/networking/virtual_network/nsg/flow_logs/flow_logs.tf, modules/networking/virtual_network/nsg/flow_logs/variables.tf, modules/networking/virtual_network/nsg/nsg_flow_logs.tf, network_security_groups.tf, networking.tf
=> Fix pre-existing network watcher  #527

examples/networking/virtual_network_gateway/104-vpn-point-to-site-gateway/configuration.tfvars, modules/networking/virtual_network_gateways/module.tf
- Adding optional section to enable p2s on virtual gateway
=> Adding p2s support to virtual gateway

modules/subscriptions/output.tf
Update import subscription id in the tfstate instead of using the logged in sub id
=> Correction on subid output for importing subscription

modules/networking/application_gateway/application_gateway.tf
=> Fix application gateway issue with empty fqdn

networking_firewall.tf
https://github.com/aztfmod/terraform-azurerm-caf/issues/617
=> Fix subnet optional in secure hub firewall

modules/compute/virtual_machine/vm_linux.tf
#615 If password_authentication is set to true, allow the user to enter password
=> Add Ability to Enter admin_password

examples/mssql_mi/200-mi-two-regions/configuration.tfvars, examples/mssql_mi/200-mi/configuration.tfvars
Fix sql mi example that failing in CI
=> fix sqlmi example to update on password handling

modules/app_insights/output.tf, modules/networking/express_route_circuit/output.tf, modules/networking/express_route_circuit_authorization/output.tf, networking_express_route.tf
Update Output.tf files  with parameter "sensitive =  true" for the following resources app_insights , express_route_circuit, express_route_circuit_authorization to fix error during the deployment.
=> Update Output.tf files  with "sensitive =  true"

modules/azuread/groups/group.tf
Code taken from Azuread_Application to allow owners to be assigned within code
=> Add Owner to Azuread group

examples/networking/private_links/endpoints/centralized/private_endpoints.tfvars, modules/networking/private_links/endpoints/subnet/diagnostic_event_hub_namespaces.tf, modules/networking/private_links/endpoints/subnet/diagnostic_storage_accounts.tf, modules/networking/private_links/endpoints/subnet/eventhub_namespaces.tf, modules/networking/private_links/endpoints/subnet/keyvaults.tf, modules/networking/private_links/endpoints/subnet/mssql_servers.tf, modules/networking/private_links/endpoints/subnet/mysql_servers.tf, modules/networking/private_links/endpoints/subnet/recovery_vaults.tf, modules/networking/private_links/endpoints/subnet/redis_cache.tf, modules/networking/private_links/endpoints/subnet/storage_accounts.tf, networking_private_links.tf
Allow specifying resource id that is created outside caf or resources from cross tenant..
=> Input resource id for privatelink

container_registry.tf, examples/compute/container_registry/200-acr-vnet/configuration.tfvars, modules/compute/container_registry/registry.tf, modules/compute/container_registry/variables.tf
Enable caf to totally disable public access with `public_network_access_enabled`
=> update ACR to support public access flag

modules/compute/virtual_machine/vm_legacy.tf
One value update did not make the previous PR
=> Update the lun value

networking.tf
Fix for vnet peering recreate when subnet is added to the vnet
=> Add lifecycle for vnet peering

modules/networking/application_gateway/application_gateway.tf
with [1], the content will never get any value
=> Updating URL rewrite rule for Application Gateway

modules/compute/virtual_machine/vm_disk.tf
Discussed with @arnaudlh regarding this regression. Disks are being forced replaced.
=> Updating VM disks lifecycle

.github/workflows/standalone-scenarios.json, data_factory.tf, data_factory_linked_services.tf, examples/data_factory/112-data_factory_linked_service_azure_databricks/README.md, examples/data_factory/112-data_factory_linked_service_azure_databricks/configuration.tfvars, examples/module.tf, examples/variables.tf, locals.combined_objects.tf, locals.tf, modules/data_factory/data_factory/module.tf, modules/data_factory/data_factory/variables.tf, modules/data_factory/linked_services/azure_databricks/README.md, modules/data_factory/linked_services/azure_databricks/main.tf, modules/data_factory/linked_services/azure_databricks/module.tf, modules/data_factory/linked_services/azure_databricks/output.tf, modules/data_factory/linked_services/azure_databricks/variables.tf
=> azurerm_data_factory_linked_service_azure_databricks

modules/data_factory/linked_services/azure_databricks/module.tf
Added the Min + Max workers for new clusters
=> Sm data factory linked service azure databricks

data_factory.tf, examples/data_factory/112-data_factory_integration_runtime_azure_ssis/configuration.tfvars, modules/data_factory/data_factory_integration_runtime_self_hosted/output.tf
=> Data Factory SSIS examples

machine_learning.tf, modules/analytics/machine_learning_compute_instance/managed_identities.tf, modules/analytics/machine_learning_compute_instance/module.tf
=> Sm machine learning compute instance

examples/storage_accounts/103-storage-account-network-rules/configuration.tfvars, modules/storage_account/storage_account.tf
Added ability to reference remote subnets for network rules in storage accounts
=> Storage remote subnet

modules/compute/virtual_machine_scale_set/vmss_linux.tf, modules/compute/virtual_machine_scale_set/vmss_windows.tf
=> Fix to #814

.github/workflows/standalone-scenarios.json, active_directory_domain_service.tf, examples/identity/active_directory_domain_service/100-active_directory_domain_service-replica/configuration.tfvars, examples/identity/active_directory_domain_service/100-active_directory_domain_service-replica/nsg.tfvars, examples/identity/active_directory_domain_service/100-active_directory_domain_service-replica/vnets.tfvars, modules/identity/active_directory_domain_service/module.tf, modules/identity/active_directory_domain_service/output.tf, modules/identity/active_directory_domain_service_replica_set/main.tf, modules/identity/active_directory_domain_service_replica_set/module.tf, modules/identity/active_directory_domain_service_replica_set/output.tf, modules/identity/active_directory_domain_service_replica_set/variables.tf
Add Azure AADDS
Add Azure AADDS replicasets
=> Update AADDS to support replica sets

examples/app_gateway/301-agw-v1/agw_application.tfvars, modules/networking/application_gateway_application/url_path_rule.tf
fix agw v1 url path map rule bug. resolved #845 
update example
=> Fix issue in Application Gateway v1 URL path map rule on delete null resource

examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/configuration.tfvars, modules/compute/virtual_machine_scale_set_extensions/custom_script.tf
Thanks for merging https://github.com/aztfmod/terraform-azurerm-caf/pull/807!
Yesterday we also tested the execution of the script extensions in both Linux and Windows (which worked eventually), but I forgot to commit a few changes at the end of the day.
This morning it seems you have also fixed the (same) remaining bugs, which I just noticed during the review of your final commits. These are some very minor changes that remained after my review, feel free to merge or discard them.
=> Final vmss custom script extension fixes

application_gateway_applications.tf, modules/networking/application_gateway_application/http_listener.tf, modules/networking/application_gateway_application/variable.tf, modules/networking/private_endpoint/private_endpoint.tf
=> Add waf policy support to application gateway v1 and fix regression bug in private endpoint

examples/compute/virtual_machine_scale_set/105-linux-win-vmss-autorepair/configuration.tfvars, modules/compute/virtual_machine_scale_set/vmss_linux.tf, modules/compute/virtual_machine_scale_set/vmss_windows.tf, modules/networking/load_balancers/output.tf
Hi,
This PR should resolve #829.
I've tried it locally, it works; delivered healthy vmss instances and is idempotent.
Please let me know if this is good enough to merge.
=> Add automatic repair to vmss, based on a lb probe.

modules/webapps/function_app/module.tf
System Identity option added to identity in function app
=> System Identity option added to identity in function app

modules/compute/virtual_machine/mssql_vm.tf, modules/compute/virtual_machine/vm_disk.tf
Random password and keyvault secret is being created for linux vm which should not happen as mssql_vm resource can only be deployed to windows vm
=> No password generated for Linux VM when deploying MSSQL

modules/storage_account/file_share/file_share.tf
=> Issue #863 - Azure file share backup

api_management.tf, examples/apim/107-api_operation_policy/configuration.tfvars, examples/apim/109-api_management_custom_domain/configuration.tfvars, modules/apim/api_management_api_operation_policy/module.tf
Fix for the example 107 API Operation Policy.
=> APIM - Example 107 - API Operation Policy FIX

examples/standalone.md
=> Update standalone.md to fix typo

modules/apim/api_management/module.tf, modules/apim/api_management_api/module.tf, modules/apim/api_management_gateway/module.tf, modules/apim/api_management_group/module.tf, modules/apim/api_management_logger/module.tf
@brianfedorcrowe 
#934 Incorrect resource type specified for APIM
-Fixes for the resource types in the name provider.
=> APIM Name Provider Resource Type Fix

main.tf, modules/compute/aks/aks.tf
This PR will allow to use Azure Key Vault Provider for Secrets Store CSI Driver in an AKS cluster
=> Add keyvault secrets provider to AKS

.github/workflows/standalone-scenarios.json, examples/module.tf, examples/monitoring/104-log_analytics_storage_insights/configuration.tfvars, examples/variables.tf, locals.tf, log_analytics.tf, modules/monitoring/log_analytics_storage_insights/README.md, modules/monitoring/log_analytics_storage_insights/main.tf, modules/monitoring/log_analytics_storage_insights/module.tf, modules/monitoring/log_analytics_storage_insights/output.tf, modules/monitoring/log_analytics_storage_insights/variables.tf
#958 
log analytics storage insights implementation.
*Pending Name Provider.
=> Adding log analytics storage insights

.github/workflows/standalone-scenarios.json, examples/compute/virtual_machine/213-vm_generic_extensions/configurations.tfvars, examples/compute/virtual_machine/214-vm-generic_extensions_complex/configurations.tfvars, examples/compute/virtual_machine_scale_set/106-vmss_monitoring/configuration.tfvars, modules/compute/virtual_machine_extensions/generic_extensions.tf, modules/compute/virtual_machine_scale_set/vmss_windows.tf, modules/compute/virtual_machine_scale_set_extensions/dependency_agent.tf, modules/compute/virtual_machine_scale_set_extensions/microsoft_monitor_agent.tf, modules/compute/virtual_machine_scale_set_extensions/variables.tf, modules/log_analytics/output.tf, virtual_machines_extensions.tf, virtual_machines_scale_sets_extensions.tf
Recreated the VMSS and Generic Extensions to match the new model.
=> Adding VMSS/VM Generic Extension and Insights 

modules/networking/application_gateway/application_gateway.tf
A few fields that are missing which I needed to implement on a project.
=> Application gateway improvements

.github/workflows/standalone-scenarios.json, examples/module.tf, examples/purview/100-purview_account/configuration.tfvars, examples/variables.tf, locals.combined_objects.tf, locals.tf, modules/purview/purview_account/README.md, modules/purview/purview_account/diagnostics.tf, modules/purview/purview_account/main.tf, modules/purview/purview_account/module.tf, modules/purview/purview_account/output.tf, modules/purview/purview_account/variables.tf, purview.tf, variables.tf
=> Purview Account

.github/workflows/standalone-scenarios.json, examples/app_config/100-simple/configuration.tfvars, examples/app_config/README.md, examples/module.tf, examples/variables.tf, modules/databases/app_config/local.dynamic_settings.tf, variables.tf
#994
Example and README.md for App Conf
=> App Conf Example

diagnostics.tf, log_analytics.tf, modules/log_analytics/solutions.tf, modules/log_analytics/variables.tf, modules/log_analytics/workspace.tf
Regressor run: https://github.com/aztfmod/terraform-azurerm-caf/actions/runs/1998338506
=> Refactor diagnostics composition

modules/compute/virtual_machine_extensions/wvd_dsc.tf, modules/compute/wvd_application_group/virtual_desktop_application_group.tf, modules/compute/wvd_host_pool/virtual_desktop_host_pool.tf, modules/compute/wvd_workspace/virtual_desktop_workspace.tf
when I have tried to deploy new wvd I have faced many issues and here is my fixes
=> Fix prefixes on Azure Virtual Desktop and host pool association

modules/webapps/function_app/module.tf
=> Add key vault reference identity to function app

examples/networking/firewall/104-firewall-force-tunnelling/configuration.tfvars, modules/networking/firewall/module.tf
=> fixed bug for azure firewall management ip id and added example

modules/azuread/applications/module.tf
=> prevent_duplicate_names instead of identifier_uris

.github/workflows/standalone-scenarios.json, examples/webapps/appservice/109-appservice-appgw/configuration.tfvars, locals.tf, modules/webapps/appservice/module.tf
---
- Support for all available parameters in ip_restriction
- Allow to reference subnet by vnet_key and subnet_key
- Add an example on how to configure an IP restricted app service in combination with appgw
```
module.azure.azurerm_app_service_virtual_network_swift_connection.vnet_config["webapp_appgw"]: Destroying... [id=/subscriptions/9f6c4025-c3e6-4d11-910a-XXXXXXXX/resourceGroups/module-test-rg-webapp-appgw/providers/Microsoft.Web/sites/module-test-app-webapp-appgw/config/virtualNetwork]
module.azure.module.application_gateways["appgw_webapp"].azurerm_application_gateway.agw: Destroying... [id=/subscriptions/9f6c4025-c3e6-4d11-910a-XXXXXXXX/resourceGroups/module-test-rg-webapp-appgw/providers/Microsoft.Network/applicationGateways/module-test-agw-appgw-webapp] …
```
=> Fix ip_restriction issues and add improvements for App Service

networking_firewall.tf
---
The firewall_policy_key was not considered when creating an azure firewall
- [x ] NO
=> fixed firewall: firewall_policy_key not considered

examples/compute/virtual_machine/111-single-linux-ansible-playbook/configuration.tfvars, examples/compute/virtual_machine/111-single-linux-ansible-playbook/nsg.tfvars, examples/compute/virtual_machine/111-single-linux-ansible-playbook/playbook.yml, examples/compute/virtual_machine/111-single-linux-ansible-playbook/runbooks.tfvars, examples/compute/virtual_machine/111-single-linux-ansible-playbook/virtual_machines.tfvars, locals.tf, modules/compute/runbooks/ansible_playbook/ansible.tf, modules/compute/runbooks/ansible_playbook/variables.tf, runbooks.tf
=> Added Ansible Playbooks for Linux VM

networking_firewall.tf
---
```
t -chdir=/tf/caf/aztfmod/examples apply -var-file /tf/caf/aztfmod/examples/networking/firewall/100-standard-firewall-legacy-pip/configuration.tfvars
```
=> Fixing #1087

examples/webapps/appservice/105-appservice-backup/configuration.tfvars, modules/webapps/appservice/main.tf, modules/webapps/appservice/module.tf, modules/webapps/appservice/storage_account.tf
=> Patch for #954

examples/webapps/appservice/101-appservice-simple/configuration.tfvars, examples/webapps/appservice/107-appservice-private/configuration.tfvars, examples/webapps/function_app/102-function_app-linux/configuration.tfvars
=> Fix ci regressor

.github/workflows/standalone-scenarios.json, examples/module.tf, examples/networking/virtual_wan/102a-vwan-hub-firewall-secured-vhub-fw-mgr/virtual_wan.tfvars, examples/variables.tf, locals.tf, modules/networking/express_route_connection/module.tf, modules/networking/virtual_hub_er_gateway_connection/er_connection.tf, modules/networking/virtual_hub_route_table_routes/module.tf, modules/networking/virtual_hub_route_table_routes/output.tf, modules/networking/virtual_hub_route_table_routes/variables.tf, networking_virtual_hub_connection.tf, networking_virtual_hub_route_table_routes.tf
---
Add support for virtual hub route table routes. Required to route traffic through secure firewall.
terraform -chdir=/tf/caf/aztfmod/examples init -upgrade
terraform -chdir=/tf/caf/aztfmod/examples apply -var-file /tf/caf/aztfmod/examples/networking/virtual_wan/102a-vwan-hub-firewall-secured-vhub-fw-mgr/virtual_wan.tfvars
=> Feature.virtual hub route table routes

data_factory.tf, modules/data_factory/data_factory/private_endpoints.tf
=> fix location variables in Data factory module

examples/networking/virtual_network_gateway/105-vpn-point-to-site-gateway-multi-auth/configuration.tfvars, modules/networking/virtual_network_gateways/module.tf
-Add p2s example / multiple authentication methods
---
- [x ] I have added example(s) inside the [./examples/] folder
- [ x] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [ x] I have checked to ensure there aren't other open Pull Requests for the same update/change?
This change will enhance the virtual network gateway module with some optional fields which are available in the base resource
- [ x] NO
Nothing special
=> Added optional attributes in vpn_client_configuration

.github/workflows/standalone-scenarios.json, examples/purview/100-purview_account/configuration.tfvars, examples/purview/101-purview_account_private_link/configuration.tfvars, modules/purview/purview_accounts/main.tf, modules/purview/purview_accounts/output.tf, modules/purview/purview_accounts/private_endpoints.tf, modules/purview/purview_accounts/variables.tf, purview.tf
=> Add support for private endpoints in Purview

examples/azuread/101-custom-role-assignable-scopes/configuration.tfvars, modules/roles/custom_roles/module.tf, modules/roles/custom_roles/variables.tf, roles.tf
---
Allow assigning scopes to custom roles.
=> Add assignable_scopes attribute to custom_roles module

roles.tf
---
Refactor the scope and principal_id and remote lifecycles
=> remove role assignment lifecycles

roles.tf
Hotfix for 5.5.7 role composition
=> Fix regression in principal_id for roles.tf

modules/networking/application_gateway_platform/application_gateway.tf
---
Add keyvault id referencing for module application_gateway_platform to support uploading of SSL cert. This is to match the functionality currently supported in the application_gateway module: https://github.com/aztfmod/terraform-azurerm-caf/blob/main/modules/networking/application_gateway/application_gateway.tf
=> Update agw platform to reference keyvault by id to get SSL cert

modules/compute/virtual_machine_scale_set_extensions/custom_script.tf
Small improvement to the custom script extension.
=> Add provision_after_extensions to custom_script extension

modules/azuread/groups/group.tf, modules/azuread/groups/output.tf, modules/azuread/groups/variables.tf
=> Added 'assignable_to_role' option for AAD groups

.github/workflows/standalone-scenarios.json, azuread_roles.tf, cosmosdb_sql_databases.tf, examples/compute/virtual_machine/215-vm-keyvault-for-windows-extension/certificates.tfvars, examples/compute/virtual_machine/215-vm-keyvault-for-windows-extension/configurations.tfvars, examples/compute/virtual_machine/215-vm-keyvault-for-windows-extension/keyvaults.tfvars, examples/compute/virtual_machine/215-vm-keyvault-for-windows-extension/networking.tfvars, examples/compute/virtual_machine/215-vm-keyvault-for-windows-extension/virtual_machines.tfvars, messaging_servicebus_namespaces.tf, modules/compute/virtual_machine_extensions/generic_extensions.tf, modules/compute/virtual_machine_extensions/keyvaultforwindows.tf, monitor_autoscale_settings.tf, mssql_servers.tf, virtual_machines_extensions.tf, virtual_machines_scale_sets.tf
---
Adding support for VM extension KeyvaultForWindows 
Run the example
=> Adding Keyvault for windows extension support and example

examples/cosmos_db/101-private-endpoint-cosmos-db/configuration.tfvars, modules/databases/cosmos_dbs/cosmosdb_account.tf
---
Provide option to control Cosmos DB public access
=> Add public control cosmos db

examples/networking/front_door/102-front_door_advanced/front_door_rules_engine.tfvars, modules/networking/frontdoor_rules_engine/module.tf
---
There is a wrong reference in response header dynamic block
=> [front door rules engine] Bugfix response header dynamic block

modules/webapps/function_app/module.tf
---
This PR fix the mapping of some values (`cors`, `ip_restriction`, `scm_ip_restriction`) on function app.
=> Fixed function_app values

.github/workflows/standalone-scenarios-longrunners.json, api_management.tf, examples/apim/116-api_management_subscription/configuration.tfvars, examples/module.tf, examples/variables.tf, locals.tf, modules/apim/api_management_subscription/main.tf, modules/apim/api_management_subscription/module.tf, modules/apim/api_management_subscription/output.tf, modules/apim/api_management_subscription/variables.tf
=> API management subscription

modules/analytics/synapse/private_endpoints.tf, modules/analytics/synapse/variables.tf, synapses.tf
---
- [Yes ] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [ Yes] I have checked to ensure there aren't other open Pull Requests for the same update/change?
Enables the passing of a private_endpoints map to the synapse_workspace module.
- [X ] NO
=> Adds support for Synapse Workspace Private Endpoints

examples/compute/virtual_machine_scale_set/106-linux-win-vmss-lb/configurations.tfvars, modules/compute/virtual_machine_scale_set/main.tf, modules/compute/virtual_machine_scale_set/variables.tf, modules/compute/virtual_machine_scale_set/vmss_linux.tf, modules/compute/virtual_machine_scale_set/vmss_windows.tf, virtual_machines_scale_sets.tf
=> Fix VM scale set LB assignment and add new LB module variable to VM scale set module

.github/workflows/standalone-scenarios.json, examples/redis_cache/103-redis-private-endpoints/configuration.tfvars, modules/redis_cache/private_endpoints.tf, modules/redis_cache/variables.tf, redis_caches.tf
---
Local.
Will include in next regressor run.
=> Add private endpoints for redis

modules/networking/firewall_policies/firewall_policy.tf
---
(https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall_policy#private_ip_ranges)
=> Added private_ip_ranges for azurerm_firewall_policy

examples/mssql_mi/200-mi-two-regions/configuration.tfvars, examples/mssql_mi/200-mi/configuration.tfvars, modules/databases/mssql_managed_instance/administrator/scripts/set_mi_ad_admin.sh, modules/databases/mssql_managed_instance/arm_sql_mi.json, modules/databases/mssql_managed_instance/main.tf, modules/databases/mssql_managed_instance/managed_instance.tf, modules/databases/mssql_managed_instance/variables.tf, msssql_managed_instances.tf
=> Support remote keyvault for SQL MI admin password

modules/networking/application_gateway_application/http_listener.tf, modules/networking/application_gateway_application/root_cert.tf, modules/networking/application_gateway_platform/application_gateway.tf
=> Updating Application Gateway TLS certificates ingestion

modules/databases/mssql_managed_instance/arm_sql_mi.json, modules/databases/mssql_managed_instance/managed_instance.tf, modules/databases/mssql_managed_instance/output.tf
=> Update SQL MI output

modules/databases/mssql_managed_instance/arm_sql_mi.json, modules/databases/mssql_managed_instance/managed_instance.tf, modules/databases/mssql_managed_instance/output.tf
Reverts aztfmod/terraform-azurerm-caf#1177
=> Revert "Update SQL MI output"

modules/databases/mssql_managed_instance/managed_instance.tf, modules/databases/mssql_managed_instance/output.tf, modules/databases/mssql_managed_instance/variables.tf, msssql_managed_instances.tf
=> Patch fixing SQL MI outputs 

modules/databases/mssql_managed_instance/managed_instance.tf
=> Update parent_id for SQL MI

modules/databases/mssql_managed_instance/managed_instance.tf
=> Update resource id SQL MI

modules/databases/mssql_managed_instance/managed_instance.tf
=> Update for SQM MI id outputs

event_hubs.tf, modules/event_hubs/namespaces/auth_rules/output.tf
---
This PR adds outputs for eventhub_namespace connection strings.
=> Added output for eventhubs auth_rules

modules/databases/mssql_managed_instance/main.tf
=> Add requestedBackupStorageRedundancy

postgresql_flexible_servers.tf
---
Similar to https://github.com/aztfmod/terraform-azurerm-caf/pull/1191 this PR fix evaluation issues for subnet
=> fix remote objects for flexible server to prevent evaluation issues

examples/compute/virtual_machine/112-ssh-key/configuration.tfvars, examples/compute/virtual_machine/112-ssh-key/readme.md, modules/compute/virtual_machine/admin_ssh_key.tf, modules/compute/virtual_machine/main.tf, modules/compute/virtual_machine/mssql_vm.tf, modules/compute/virtual_machine/vm_linux.tf
---
```
virtual_machine_settings = {
linux = {
name                            = "example_vm1"
size                            = "Standard_F2"
admin_username                  = "adminuser"
disable_password_authentication = true
admin_ssh_keys = {
admin = {
#
keyvault_key = "example_vm_rg1"
secret_name  = "ssh-key"
}
}
...
}
```
=> Add support for admin_ssh_keys for linux vm

examples/compute/virtual_machine/100-single-linux-vm/configuration.tfvars, examples/compute/virtual_machine/112-ssh-key/configuration.tfvars, examples/compute/virtual_machine/112-ssh-key/readme.md, modules/compute/virtual_machine/admin_ssh_key.tf, modules/compute/virtual_machine/main.tf, modules/compute/virtual_machine/mssql_vm.tf, modules/compute/virtual_machine/shutdown_schedule.tf, modules/compute/virtual_machine/vm_linux.tf
---
```
virtual_machines = {
example_vm1 = {
resource_group_key = "vm_region1"
provision_vm_agent = true
boot_diagnostics_storage_account_key = "bootdiag_region1"
os_type = "linux"
keyvault_key = "example_vm_rg1"
shutdown_schedule = {
enabled = true
daily_recurrence_time = "0100"
timezone              = "Singapore Standard Time"
notification_settings = {
enabled         = true
time_in_minutes = "60"
webhook_url     = "https://sample-webhook-url.example.com"
}
}
...
}
```
=> Add support for shutdown_schedule

locals.tf, main.tf, modules/analytics/synapse/workspace.tf, modules/azuread/applications/module.tf, modules/azuread/credentials/password_rotation.tf, modules/azuread/service_principal_password/module.tf, modules/azuread/users/user.tf, modules/compute/aks/aks.tf, modules/compute/virtual_machine/mssql_vm.tf, modules/compute/virtual_machine/vm_legacy.tf, modules/compute/virtual_machine/vm_windows.tf, modules/compute/virtual_machine_scale_set/vmss_linux.tf, modules/compute/virtual_machine_scale_set/vmss_windows.tf, modules/databases/mariadb_server/server.tf, modules/databases/mssql_managed_instance/managed_instance.tf, modules/databases/mssql_server/server.tf, modules/databases/postgresql_flexible_server/server.tf, modules/databases/postgresql_server/server.tf, modules/random_string/module.tf, random_string.tf
Update from ```number``` to  ```numeric```
=> Update for random provider

app_services.tf, modules/webapps/appservice/private_endpoint.tf, modules/webapps/appservice/variables.tf
=> Add private endpoint support for webapps

.github/workflows/standalone-scenarios-additional.json, .github/workflows/standalone-scenarios.json, aks_clusters.tf, modules/compute/aks/aks.tf, modules/databases/mssql_server/server.tf, modules/databases/mysql_flexible_server/server.tf
=> CI feedbacks fixes

.github/workflows/standalone-scenarios.json, examples/networking/ip_group/102-remote-rg-ip_group/configuration.tfvars, examples/networking/ip_group/102-remote-rg-ip_group/networking.tfvars, modules/networking/ip_group/module.tf, modules/networking/ip_group/variables.tf, networking_ip_groups.tf
---
This allows to create an IP group inside a remote resource group.
=> Adding remote resource group support to IP groups

examples/keyvault/101-keyvault-policies/keyvaults.tfvars, modules/security/keyvault/private_endpoints.tf
---
Added the possibility to deploy a keyvault's private endpoint in a remote resource group.
=> Allows to deploy a keyvault's private endpoint in a remote resource group.

.github/workflows/standalone-scenarios.json, examples/storage_accounts/109-storage-account-advanced-options-cmk/configuration.tfvars, modules/security/keyvault_key/output.tf, modules/storage_account/encryption_scope/module.tf, modules/storage_account/encryption_scope/variables.tf, modules/storage_account/managed_identities.tf, modules/storage_account/storage_account.tf, modules/storage_account/variables.tf, storage_accounts.tf
---
This PR update the customer encryption scenarios for storage_accounts.
Add support for:
- reference an encryption key from a remote keyvault or by resource id
- queue_encryption_key_type
- table_encryption_key_type
- infrastructure_encryption_enabled
- encryption_scopes (CMK with versioned and versionless key for rotation)
- add support for user msi for storage accounts
Examples / storage_accounts/109-storage-account-advanced-options-cmk contains an example.
```
storage_accounts = {
st = {
...
queue_encryption_key_type = "Account"
table_encryption_key_type = "Account"
infrastructure_encryption_enabled = true
encryption_scopes = {
versioned = {
name                               = "versioned"
source                             = "Microsoft.KeyVault"
infrastructure_encryption_required = …
```
=> Add storage accounts encryption scopes and update CMK support

networking_virtual_hub_connection.tf
=> Fix vnet connection propagation to route tables ids

modules/compute/container_group/container_group.tf
=> Update optional attributes on dns_config

examples/app_gateway/210-agw-with-keyvault/application_gateways.tfvars, modules/networking/application_gateway/application_gateway.tf
---
This PR fixes the ssl_profile configuration for Application Gateway
=> Fix ssl_profile for app gateway

modules/networking/virtual_network/module.tf, modules/networking/virtual_network/subnet/subnet.tf
=> Fix a lifecycle on adding new subnet to exist vnet

.github/workflows/standalone-scenarios.json, examples/variables.tf, examples/webapps/static_site/101-simple-static-web-app/configuration.tfvars, locals.tf, modules/webapps/static_site/diagnostic.tf, modules/webapps/static_site/main.tf, modules/webapps/static_site/module.tf, modules/webapps/static_site/output.tf, modules/webapps/static_site/variables.tf, static_sites.tf
---
Adding support for "azurerm_static_site".
Open: https://github.com/aztfmod/terraform-provider-azurecaf/issues/178
=> feat: add new module 'webapps/static_site'

modules/webapps/appservice/module.tf
=> #1159 add health check and custom hostname binding for app service

.github/workflows/standalone-scenarios.json, examples/role_mapping/101-function-app-managed-identity/configuration.tfvars, modules/webapps/function_app/output.tf, roles.tf
---
Run the example in `examples/role_mapping/101-function-app-managed-identity`
=> Function App System-Assigned Managed Identity - RBAC Assignments

examples/diagnostics_profiles/202-reuse-existing-log-analytics/diagnostics_destinations.tfvars, modules/networking/virtual_network/nsg/flow_logs/flow_logs.tf
Fixing bug on Flow logs issue #985
=> Add workspace_id literal to diagnostics for NSG flow logs support

examples/app_gateway/301-agw-v1/agw_application.tfvars, modules/networking/application_gateway_application/frontend_ports.tf, modules/networking/application_gateway_application/http_listener.tf, modules/networking/application_gateway_application/http_settings.tf, modules/networking/application_gateway_application/probe.tf, modules/networking/application_gateway_application/scripts/delete_resource.sh, modules/networking/application_gateway_application/scripts/set_resource.sh
=> application_gateway_application: Fixed probe dependency and added custom_port capability for application gateway application configuration. 

.devcontainer/docker-compose.yml, .github/workflows/standalone-regressor-tf100.yaml, .github/workflows/standalone-tf100.yaml, .pre-commit-config.yaml, rover_on_ssh_host.yml
=> July 2022 rover update

modules/webapps/function_app/output.tf
=> Adding rbac_id for function_app

examples/mssql_server/108-sqlserver-db-diagnostics/configurations.tfvars, examples/mysql_flexible_server/100-simple-mysql-flexible/configuration.tfvars, examples/mysql_flexible_server/101-delegated-subnet-with-fw-rule/configuration.tfvars, examples/networking/firewall/101-simple-firewall/configuration.tfvars, examples/networking/firewall/104-firewall-force-tunnelling/configuration.tfvars, examples/storage_accounts/100-simple-storage-account-diagnostics/diagnostics.tfvars, modules/databases/mssql_database/database.tf, modules/webapps/static_site/module.tf
Update diagnostics definitions and other glitches found in regressos CI run.
=> Update examples based on CI feedbacks

examples/shared_image_gallery/102-packer_build_linux/packer_files/build.pkr.hcl, modules/shared_image_gallery/packer_build/packer.tf
This enhancement allows to configure os_disk_size_gb to support building a larger image (e.g. https://github.com/actions/virtual-environments)
=> Allow os_disk_size_gb to be configured

modules/databases/mssql_server/server.tf
=> Remove mssql server admin condition

virtual_machines_scale_sets.tf
---
Fix for issue mentioned in https://github.com/aztfmod/terraform-azurerm-caf/issues/1307
=> Bring back LB variables in VMSS

dynamic_secrets.tf, examples/compute/container_groups/100-aci-rover-github-runner/container_groups.tfvars, modules/azuread/groups/group.tf, modules/compute/container_group/container_group.tf, modules/compute/container_group/locals.tf, modules/compute/container_group/variable_from_command/module.tf, modules/compute/container_group/variable_from_command/variables.tf, modules/compute/container_group/variables_from_command.tf, roles.tf, storage_account_blobs.tf, storage_container.tf
=> Adding deferred role assignment feature

.github/workflows/standalone-scenarios-longrunners.json, api_management.tf, examples/apim/117-api_management_product/configuration.tfvars, examples/module.tf, examples/variables.tf, locals.combined_objects.tf, locals.tf, modules/apim/api_management_product/main.tf, modules/apim/api_management_product/module.tf, modules/apim/api_management_product/output.tf, modules/apim/api_management_product/variables.tf, modules/apim/api_management_subscription/module.tf, modules/apim/api_management_subscription/variables.tf
=> Add support for api management product

modules/compute/virtual_machine_scale_set/vmss_linux.tf
---
- virtual_machine_scale_sets must have autoscaled = true
- at least 1 network_interfaces nic with a load_balancers block
=> Fixing load_balancer_backend_address_pool_ids value for autoscaled virtual_machine_scale_set resource

examples/storage_accounts/107-storage-account-management-policy/configuration.tfvars, modules/storage_account/management_policy/management_policy.tf
---
Adds support for access time based rules for blob lifecycle management.
=> Add blob lifecycle management rules based on access time

automation_runbooks.tf, automation_schedules.tf, examples/automation/104-automation-schedule-runbook/configuration.tfvars, examples/module.tf, examples/variables.tf, locals.tf, modules/automation/automation_runbook/main.tf, modules/automation/automation_runbook/module.tf, modules/automation/automation_runbook/output.tf, modules/automation/automation_runbook/variables.tf, modules/automation/automation_schedule/main.tf, modules/automation/automation_schedule/module.tf, modules/automation/automation_schedule/output.tf, modules/automation/automation_schedule/variables.tf, modules/automation/module.tf, modules/automation/variables.tf
=> Adding azure automation runbook and schedule

.devcontainer/docker-compose.yml, .github/workflows/standalone-regressor-tf100.yaml, .github/workflows/standalone-scenarios.json, .github/workflows/standalone-tf100.yaml, .pre-commit-config.yaml, azure_redhat_openshift.tf, examples/compute/azure_redhat_openshift/101_basic_private_cluster/aro.tfvars, examples/compute/azure_redhat_openshift/101_basic_private_cluster/principal.tfvars, examples/compute/azure_redhat_openshift/101_basic_private_cluster/vnet.tfvars, examples/compute/azure_redhat_openshift/102_basic_public_cluster/aro.tfvars, examples/compute/azure_redhat_openshift/102_basic_public_cluster/principal.tfvars, examples/compute/azure_redhat_openshift/102_basic_public_cluster/vnet.tfvars, examples/module.tf, examples/variables.tf, locals.tf, main.tf, modules/azuread/applications/output.tf, modules/azuread/applications_v1/output.tf, modules/azuread/groups/output.tf, modules/compute/azure_redhat_openshift/aro.tf, modules/compute/azure_redhat_openshift/locals.tf, modules/compute/azure_redhat_openshift/main.tf, modules/compute/azure_redhat_openshift/outputs.tf, modules/compute/azure_redhat_openshift/variables.tf, modules/messaging/eventgrid/eventgrid_event_subscription/output.tf, rover_on_ssh_host.yml
=> Adding Azure Red Hat OpenShift

modules/networking/application_gateway_application/http_settings.tf, modules/networking/application_gateway_application/probe.tf, modules/networking/application_gateway_application/root_cert.tf, modules/networking/application_gateway_application/ssl_cert.tf
=> Bug/agw ssl_cert dependencies

examples/app_gateway/301-agw-v1/agw_application.tfvars, modules/databases/mssql_server/server.tf, modules/networking/application_gateway_application/request_routing_rule.tf
Reverting couple of changes from #1368
=> Fixing 1368 regressions

.github/workflows/standalone-scenarios.json, databricks.tf, examples/databricks/102-premium-databricks-vnet-private-endpoint/configuration.tfvars, modules/analytics/databricks_workspace/private_endpoint.tf, modules/analytics/databricks_workspace/variables.tf
---
Add Private Endpoint support for Databricks
Run example in the normal way:
```
cd /tf/caf/examples
az login
terraform init
terraform plan -var-file databricks/102-premium-databricks-vnet-private-endpoint/configuration.tfvars
terraform apply -var-file databricks/102-premium-databricks-vnet-private-endpoint/configuration.tfvars
terraform destroy -var-file databricks/102-premium-databricks-vnet-private-endpoint/configuration.tfvars
```
=> Add Private Endpoint support for Databricks

.github/workflows/standalone-scenarios.json, examples/compute/virtual_machine/216-vm-linux_diagnostic_extensions/configurations.tfvars, examples/compute/virtual_machine/216-vm-linux_diagnostic_extensions/diagnostics/filelogs.json, examples/compute/virtual_machine/216-vm-linux_diagnostic_extensions/diagnostics/ladcfg.json, examples/module.tf, modules/compute/virtual_machine_extensions/LinuxDiagnostic.tf, virtual_machines_extensions.tf
=> Add vm-linux_diagnostic_extensions #1423

.github/workflows/standalone-scenarios.json, examples/azuread/105-azuread-application-with-optional-claims/configuration.tfvars, modules/azuread/applications/module.tf, modules/azuread/applications_v1/azuread_application.tf
=> Add optional_claims for azuread applications

event_hubs.tf
---
- [] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
Simply rendering output from the event_hubs module
n/a
=> Adding output from module.event_hubs

modules/analytics/synapse/workspace.tf
=> Synapse fix aad devops and github repos parameters

examples/networking/lb/100-lb/configurations.tfvars, lb.tf, local.remote_objects.tf, locals.combined_objects.tf, modules/networking/lb_rule/module.tf, modules/networking/lb_rule/variables.tf
=> Add references for probe and backend_address_pool to lb_rule

.github/workflows/standalone-scenarios.json, examples/compute/virtual_machine_scale_set/109-linux-win-vmss-generic-extension/configuration.tfvars, modules/compute/virtual_machine_scale_set_extensions/generic_extensions.tf, virtual_machines_scale_sets_extensions.tf
---
Add support for Virtual Machine Scale Sets generic extensions.
=> Add support for VMSS generic extensions

examples/networking/ddos/configuration.tfvars
=> Adding DDOS Examples 

azurerm_application_insights.tf, examples/app_insights/103-web-test/configuration.tfvars, examples/module.tf, examples/variables.tf, local.remote_objects.tf, locals.combined_objects.tf, locals.tf, modules/app_insights/standard_web_test/main.tf, modules/app_insights/standard_web_test/module.tf, modules/app_insights/standard_web_test/output.tf, modules/app_insights/standard_web_test/variables.tf, modules/monitoring/monitor_metric_alert/module.tf
=> Add standard web test

modules/analytics/synapse/spark_pool/spark_pool.tf
=> Fix Issue - Minor changed - Adds sparkconfig as dynamic attribute on sparkpool

modules/analytics/synapse/workspace.tf
=> Fix Issue - Minor changes - Allow null values in synapse dynamic parameters

examples/webapps/appservice/109-appservice-appgw/configuration.tfvars, examples/webapps/appservice/109-appservice-appgw/waf.tfvars, modules/networking/application_gateway/application_gateway.tf
---
Tested with updated example "109-appservice-appgw".
=> Fix issue with missing parameter priority on application_gateway_applications resource - dynamic block request_routing_rules

.devcontainer/docker-compose.yml, .github/workflows/standalone-regressor-tf100.yaml, .github/workflows/standalone-tf100.yaml, examples/networking/ddos/configuration.tfvars, examples/webapps/appservice/109-appservice-appgw/configuration.tfvars, modules/networking/application_gateway/application_gateway.tf, modules/redis_cache/output.tf, rover_on_ssh_host.yml
=> Update rover jan 2023

roles.tf
=> Add service roles for wvd objects

examples/networking/firewall/103-firewall-policies/configuration.tfvars, modules/networking/firewall_network_rule_collections/network_rule_collection.tf
---
Performed tests in an isolated environment
=> feat: Allow specifying of destnation FQDNs in the firewall policy

examples/compute/azure_redhat_openshift/101_basic_private_cluster/aro.tfvars, examples/compute/azure_redhat_openshift/102_basic_public_cluster/aro.tfvars, examples/cosmos_db/101-decomposed-cosmosdb-sql/sql_databases.tfvars, examples/data_protection/100-backup-vault-blob-storage/configuration.tfvars, examples/networking/front_door/100-simple-front_door/diagnostics_destinations.tfvars, examples/networking/front_door/102-front_door_advanced/diagnostics_destinations.tfvars, examples/storage_accounts/107-storage-account-management-policy/configuration.tfvars, modules/networking/load_balancers/load_balancers.tf, modules/networking/network_security_group/module.tf
- Update examples for SA, AFD, ARO, Cosmos DB. 
- Update to always have upper-case for load-balancers and NSG.
=> Update examples and improve NSG and load balancer

locals.combined_objects.tf, roles.tf
---
perform a role mapping on an existing route table. example code below.
```
role_mapping = {
built_in_role_mapping = {
route_tables = { 
route_table1 = {
"Network Contributor" = {
managed_identities = {
keys = ["aks_identity"]
}
}
}
}
}
}
```
=> feature: route table role mapping support

examples/compute/container_groups/100-aci-rover-github-runner/container_groups.tfvars, examples/messaging/web_pubsub/103-web-pubsub-keyvault/configuration.tfvars, examples/storage_accounts/109-storage-account-advanced-options-cmk/configuration.tfvars, modules/azuread/groups/output.tf, modules/databases/mssql_server/server.tf
Fix the CI examples failing on March 16 2023
=> Update pipelines & test cases

modules/azuread/applications_v1/azuread_application.tf
=> Fix owners for azuread groups

modules/compute/aks/aks.tf
---
Tested deployment of AKS with AGIC platform and azurerm 3.46.0.
=> blinQ: Update aks.tf based on properties for azurerm 3.46.0

.devcontainer/docker-compose.yml, examples/networking/private_dns_vnet_link/100_pvtdns_vnetlink/configuration.tfvars, modules/networking/private-dns/output.tf, modules/networking/private_dns_vnet_link_v1/main.tf, modules/networking/private_dns_vnet_link_v1/module.tf, modules/networking/private_dns_vnet_link_v1/output.tf, modules/networking/private_dns_vnet_link_v1/variables.tf, networking_private_dns.tf
=> Update Private DNS networking links to support remote/local dns_servers and vnet

modules/networking/private_dns_vnet_link_v1/module.tf
=> Add try block to check the base tags exists or not

examples/compute/virtual_machine/100-single-linux-vm/configuration.tfvars, examples/compute/virtual_machine/101-single-windows-vm/configuration.tfvars, modules/compute/virtual_machine/vm_linux.tf, modules/compute/virtual_machine/vm_windows.tf
=> Add patch_mode argument for windows and linux virtual machine

.devcontainer/docker-compose.yml, examples/storage_container/101-storage_container/configuration.tfvars, roles.tf
=> Add msi ad groups and sp to deferred role assignment

modules/security/keyvault_certificate_request/global_sign.tf, modules/security/keyvault_certificate_request/main.tf
=> Enhancement: Cert request add support for remote dynamic secret reference

modules/databases/mssql_server/main.tf, modules/databases/mssql_server/output.tf, modules/databases/mssql_server/private_endpoints.tf, modules/databases/mssql_server/security_alert.tf, modules/databases/mssql_server/server.tf, modules/databases/mssql_server/variables.tf, mssql_servers.tf, variables.tf
=> Tags update for MSSQQL private endpoints

.github/workflows/standalone-scenarios.json, examples/azuread/106-azuread-application-with-api-scopes/configuration.tfvars, modules/azuread/applications/module.tf, modules/azuread/applications_v1/azuread_application.tf
---
Allow to configure Azure AD App Registration API configuration, including the OAuth Permission Scopes.
=> Add App Registration API and OAuth Permission Scopes

examples/outputs.tf, main.tf, modules/databases/mssql_managed_instance_v1/tde/main.tf
=> Set azurerm provider to 3.53.0 and clean-up

modules/networking/virtual_wan/virtual_hub/point_to_site_gateway.tf, modules/networking/virtual_wan/virtual_hub/site_to_site_gateway.tf
=> Update create timeout from 60m to 120m

modules/apim/api_management/module.tf
=> Fixes issue #1593

examples/azuread/106-azuread-application-with-api-scopes/configuration.tfvars, modules/azuread/applications/module.tf, modules/azuread/applications_v1/azuread_application.tf
=> Fix example azuread 106

modules/networking/virtual_network/module.tf
---
I added the support of setting a custom bgp_community on VNET.
=> Adding the support of custom bgp_community on VNET

examples/networking/virtual_network_gateway/101-vpn-site-to-site/configuration.tfvars, examples/networking/virtual_network_gateway/102-vpn-site-to-site-active-active/configuration.tfvars, examples/networking/virtual_network_gateway/103-vpn-site-to-site-connection/configuration.tfvars, examples/networking/virtual_network_gateway/104-vpn-point-to-site-gateway/configuration.tfvars, examples/networking/virtual_network_gateway/105-vpn-point-to-site-gateway-multi-auth/configuration.tfvars
This PR fixes the CI failing due to a change in the CKU case.
https://github.com/aztfmod/terraform-azurerm-caf/actions/runs/4848918169/jobs/8695256173
---
- [ x] I have added example(s) inside the [./examples/] folder
- [x ] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [ x] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [ x] I have checked to ensure there aren't other open Pull Requests for the same update/change?
- [ x] NO
=> Update Sku from VPN to Vpn

examples/mssql_mi/200-mi-native-two-regions/managed_databases.tfvars, examples/mssql_mi/200-mi-native-two-regions/managed_instances.tfvars, examples/mssql_mi/200-mi-native-two-regions/nsg.tfvars, main.tf, modules/databases/mssql_managed_instance_v1/failover_group/main.tf, modules/databases/mssql_managed_instance_v1/failover_group/mi_failover_group.tf
SQL MI native bug bash:
- Fixes NSG, lifecyle
---
=> SQL MI native bug bash

examples/azuread/107-azuread-application-with-single-page-application/configuration.tfvars, modules/azuread/applications/module.tf, modules/azuread/applications_v1/azuread_application.tf
---
add support for single page application to both azuread_app and azure_application modules.
=> add support for single page application to app registrations

.github/workflows/landingzone-scenarios.yaml, .github/workflows/phases.yaml, .github/workflows/rover.yaml
=> Fix sqlmi workflows

.devcontainer/docker-compose.yml, .github/workflows/standalone-regressor-tf100.yaml, .github/workflows/standalone-scenarios.json, .github/workflows/standalone-tf100.yaml, examples/main.tf, examples/variables.provider.tf, rover_on_ssh_host.yml
Misc pipeline feedbacks.
Standalone: https://github.com/aztfmod/terraform-azurerm-caf/actions/runs/5012277509
Long runners: https://github.com/aztfmod/terraform-azurerm-caf/actions/runs/5012283345
Regressor: https://github.com/aztfmod/terraform-azurerm-caf/actions/runs/5012286682
=> Pipelines feedbacks

modules/databases/mssql_managed_instance/managed_instance.tf
=> Patch.sqlmi fix depends_on issue within sqlmi instance v0

locals.combined_objects.tf
=> Fix combined_objects_azuread_service_principals

modules/azuread/applications_v1/azuread_application.tf
=> Fix id_token_issuance_enabled for azuread

.devcontainer/docker-compose.yml, examples/keyvault/102-keyvault-cert-issuer/configuration.tfvars, keyvault_certificate_issuers.tf
=> Enhancement: add support for remote dynamic secret reference for cert issuer

examples/compute/virtual_machine/101-single-windows-vm/configuration.tfvars, examples/compute/virtual_machine/101-single-windows-vm/scripts/custom.ps1
---
- [ X ] I have added example(s) inside the [./examples/] folder
- [ X ] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [ X ] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [ X ] I have checked to ensure there aren't other open Pull Requests for the same update/change?
- [ X ] NO
=> Adding custom data example to load a file

examples/apim/103-api_operations/configuration.tfvars, examples/apim/106-api_operation_tag/configuration.tfvars, examples/apim/107-api_operation_policy/configuration.tfvars, examples/main.tf, main.tf, modules/apim/api_management_api_operation/module.tf, modules/apim/api_management_api_operation/variables.tf
#1520 Query Parameters in apim operations not working as intended
---
This PR fixes the api_management_api_operation issue reported in the error 1520
As per https://registry.terraform.io/providers/hashicorp/azurerm/3.57.0/docs/resources/api_management_api_operation
=> Fix.1520 - Query Parameters in apim operations not working as intended

modules/diagnostics/module.tf
Refactor ```log``` to ```enable_log``` for azurerm_monitor_diagnostic_setting
=> Refactor log to enabled_log

examples/networking/virtual_network_gateway/104-vpn-point-to-site-gateway/configuration.tfvars, examples/networking/virtual_network_gateway/105-vpn-point-to-site-gateway-multi-auth/configuration.tfvars, modules/networking/private-dns-resolvers/module.tf, modules/networking/private_dns_resolvers_dns_forwarding_rulesets/module.tf, modules/networking/private_dns_resolvers_inbound_endpoints/module.tf, modules/networking/private_dns_resolvers_outbound_endpoints/module.tf, modules/networking/private_dns_resolvers_virtual_network_links/module.tf, modules/networking/virtual_network_gateways/module.tf, modules/networking/virtual_network_gateways/variables.tf, networking_vngw.tf
---
This PR allows a VPN Gateway to reference a standalone virtual_subnet
=> Update VPN GW to support virtual_networks + patch pdns resolvers

modules/networking/virtual_network_gateways/module.tf, modules/networking/virtual_network_gateways/variables.tf, networking_vngw.tf
=> Add bootstrap_root_ca_public_pem to vpngw

keyvault_certificate_requests.tf
=> Fix null value for certificate requests

roles.tf
---
The implementation does not support applying Azure RBAC roles for the Azure Service Bus Namespaces
```
services_roles = {
...
machine_learning_compute_instance          = module.machine_learning_compute_instance
machine_learning_workspaces                = local.combined_objects_machine_learning
managed_identities                         = local.combined_objects_managed_identities
management_group                           = local.management_groups
mssql_databases                            = local.combined_objects_mssql_databases
mssql_elastic_pools                        = local.combined_objects_mssql_elastic_pools
mssql_managed_databases                    = local.combined_objects_mssql_managed_databases
...
}
```
These changes support it.
```
services_roles = {
... …
```
=> Add Azure RBAC roles for Azure Service Bus Namespace

examples/cosmos_db/100-cosmos-db-sql-role-mapping/configuration.tfvars, modules/databases/cosmos_dbs/cosmosdb_account.tf
---
I added new parameters for the managing security in the Cosmos DB Account (https://azure.github.io/cloud-scale-data-for-devs-guide/security.html#role-based-access-control)
=> Add missed parameters for the Azure Cosmos DB Account

modules/azuread/applications/module.tf
---
Fixed a bad variable mapping
=> Azuread application incorrect var name

examples/networking/dns_zones/100-simple-dns_zone/dns_zones.tfvars
=> mx and txt records for dns_zones

azuread_users.tf, dynamic_secrets.tf, main.tf, modules/security/keyvault/keyvault.tf, modules/storage_account/storage_account.tf, roles.tf, roles_scope.tf
---
This PR add various fixes for the caf_launchpad pipeline.
=> Fix for ci caf_launchpad

.github/workflows/standalone-scenarios.json, app_config.tf, examples/app_config/101-private-link/configuration.tfvars, modules/databases/app_config/app_config.tf, modules/databases/app_config/private_endpoints.tf, modules/databases/app_config/variables.tf, modules/networking/private_links/endpoints/subnet/app_config.tf, networking_private_links.tf
---
Add Private Link endpoints to the App Configuration module, as well as in the Key Vault.
=> Add Private Link endpoints for the App Configuration module

modules/networking/application_gateway/application_gateway.tf
=> Added default ssl_policy block to AGW

.github/workflows/standalone-networking.json, examples/networking/app_gateway/303-ssl-profile/agw_application.tfvars, examples/networking/app_gateway/303-ssl-profile/agw_platform.tfvars, examples/networking/app_gateway/303-ssl-profile/certificates.tfvars, examples/networking/app_gateway/303-ssl-profile/configuration.tfvars, examples/networking/app_gateway/303-ssl-profile/keyvaults.tfvars, examples/networking/app_gateway/303-ssl-profile/managed_identities.tfvars, examples/networking/app_gateway/303-ssl-profile/network_security_group_definition.tfvars, examples/networking/app_gateway/303-ssl-profile/networking.tfvars, modules/networking/application_gateway_platform/application_gateway.tf
---
Similar fix as in https://github.com/aztfmod/terraform-azurerm-caf/pull/1711, for the application gateway platform now.
Run `terraform plan` for the added example and verify that the ssl profile's ssl policy is correctly planned.
=> Add example and fix for app gateway platform ssl profile

networking_firewall_policy.tf
=> Improve resource_group lookup fw policy

examples/app_gateway/302-listener-ssl-policy/agw_application.tfvars, modules/networking/application_gateway_application/http_settings.tf
=> Backend port and protcol might be different than front end port and protocol. Added port and protocol as optional properties to http_settings.

main.tf, maps_account.tf
PR to update providers to latest
=> Upgrade providers

azuread_groups.tf, modules/networking/private_dns_resolvers_inbound_endpoints/main.tf
=> Fix minor issues, tag + azuread_group_membership

examples/variables.tf, modules/networking/virtual_wan/virtual_hub/virtual_hub.tf
=> added hub_routing_preference to azurerm_virtual_hub

modules/databases/mssql_managed_database_v1/var/settings/srtdays.tf
=> Fix regression sqlmi

.github/workflows/standalone-scenarios-azuread.json, examples/azuread/108-azuread-application-with-app-roles/configuration.tfvars, modules/azuread/applications_v1/azuread_application.tf
=> Add app_roles for azuread_application

examples/compute/kubernetes_services/108-single-cluster-remote-adgroup-admin/aks.tfvars, modules/compute/aks/aks.tf
---
support msi_auth_for_monitoring_enabled flag in aks
=> add msi_auth_for_monitoring_enabled  flag in aks oms agent

modules/webapps/asev3/module.tf
=> Updated Cluster Settings for ASEV3 module

.devcontainer/docker-compose.yml, .github/workflows/landingzone-scenarios.yaml, .github/workflows/rover.yaml, .github/workflows/standalone-compute.yaml, .github/workflows/standalone-networking.yaml, .github/workflows/standalone-regressor-tf100.yaml, .github/workflows/standalone-tf100.yaml, compute_virtual_machines_extensions.tf, rover_on_ssh_host.yml
Fixing the bug in ```215-vm-keyvault-for-windows-extension```
=> Fix KeyVault Windows VM Extension

modules/recovery_vault/recovery_vault.tf
Add immutability and public_network_access_enabled to Recovery Vault
=> Add immutability and public_network_access_enabled to Recovery Vault

modules/recovery_vault/backup_policies_vm.tf
Added option policy_type to be able to create "Enhanced Backup" Policies.
Create a Recovery Vault with a policy with policy_type = "V2"
=> Added policy_type to Recovery Vault Backup Policies

eventgrid.tf
=> Added tags to eventgrid resources

examples/networking/app_gateway/301-agw-v1/agw_application.tfvars, modules/networking/application_gateway_application/scripts/set_resource.sh, modules/networking/application_gateway_application/url_path_map.tf
Resolved (https://github.com/aztfmod/terraform-azurerm-caf/issues/1840)
---
=> Resolved #1840 Issue with updating url_path_map

modules/event_hubs/namespaces/event_hub_namespaces.tf
---
Fix for [#1881](https://github.com/aztfmod/terraform-azurerm-caf/issues/1881)
=> fix(azurerm_eventhub_namespace): fixing for_each reference

examples/webapps/appservice/103-appservice-extend/configuration.tfvars, modules/webapps/appservice/module.tf, modules/webapps/appservice/slot.tf
---
Add scm_ip_restriction for webapps
=> feat: Add scm_ip_restriction for webapps

.github/workflows/standalone-scenarios.json, examples/load_test/100-load-test/configuration.tfvars, examples/module.tf, examples/variables.tf, load_test.tf, locals.combined_objects.tf, locals.tf, modules/load_test/load_test.tf, modules/load_test/main.tf, modules/load_test/managed_identities.tf, modules/load_test/output.tf, modules/load_test/variables.tf, variables.tf
---
This adds the azurerm_load_test resource
=> feat(load_test): Adding azurerm_load_test resource

.github/workflows/standalone-scenarios.json, data_explorer.tf, examples/data_explorer/107-private-endpoint/configuration.tfvars, modules/databases/data_explorer/kusto_clusters/module.tf, modules/databases/data_explorer/kusto_clusters/private_endpoint.tf, modules/databases/data_explorer/kusto_clusters/variables.tf, modules/networking/private_endpoint/main.tf
=> Kusto cluster private endpoint

.github/workflows/standalone-scenarios.json, examples/postgresql_flexible_server/104-private-endpoint/configuration.tfvars, modules/databases/postgresql_flexible_server/private_endpoint.tf, modules/databases/postgresql_flexible_server/variables.tf, postgresql_flexible_servers.tf
---
This adds private endpoint feature to postgresql_flexible_servers configuration
=> Postgresql flexible server private endpoint

examples/postgresql_flexible_server/102-advanced-postgresql-flexible/configurations.tfvars, examples/postgresql_flexible_server/103-simple-postgresql-flexible-with-az-auth/configuration.tfvars, modules/databases/postgresql_flexible_server/server.tf, postgresql_flexible_servers.tf
=> feat(azurerm_postgresql_flexible_server): add Entra ID administrator

examples/role_mapping/102-azure-openai-managed-identity/configuration.tfvars, roles.tf
=> MSI role assignment for accessing the Azure Open AI service

function_app.tf, modules/webapps/function_app/diagnostic.tf, modules/webapps/function_app/variables.tf
---
Add diagnostic profiles on function apps
=> Add diagnostic profiles on function apps

roles.tf
=> fix(connection-monitors): Adding monitor_action_groups to rbac scopes

examples/compute/virtual_machine/212-vm-disk-encryption-set/configurations.tfvars, modules/compute/virtual_machine/vm_disk.tf, modules/compute/virtual_machine/vm_linux.tf, modules/compute/virtual_machine/vm_windows.tf
=> Add disk_encryption_set_id support to VM module

.devcontainer/docker-compose.yml, .github/workflows/landingzone-scenarios.yaml, .github/workflows/rover.yaml, .github/workflows/standalone-compute.yaml, .github/workflows/standalone-networking.yaml, .github/workflows/standalone-regressor-tf100.yaml, .github/workflows/standalone-tf100.yaml, examples/compute/azure_redhat_openshift/101_basic_private_cluster/aro.tfvars, examples/compute/azure_redhat_openshift/102_basic_public_cluster/aro.tfvars, examples/compute/kubernetes_services/109-single-cluster-istio/aks.tfvars, rover_on_ssh_host.yml
- Update rover to Terraform 1.8.1
- Housekeeping pipelines before overall update
- Housekeeping examples
=> Terraform 1.8.1 and housekeeping

.devcontainer/docker-compose.yml, .github/workflows/landingzone-scenarios.yaml, .github/workflows/rover.yaml, .github/workflows/standalone-compute.yaml, .github/workflows/standalone-networking.yaml, .github/workflows/standalone-regressor-tf100.yaml, .github/workflows/standalone-tf100.yaml, rover_on_ssh_host.yml
Using TF 1.7.5 as 1.8.0 crashes, 1.8.1 and 1.8.2 are dramatically slow :)
=> Rover with Terraform 1.7.5

.github/workflows/standalone-scenarios-longrunners.json, examples/mssql_mi/200-mi/configuration.tfvars, examples/mssql_mi/200-mi/nsg.tfvars, modules/databases/mssql_managed_instance/private_endpoints.tf, modules/databases/mssql_managed_instance/variables.tf, modules/databases/mssql_managed_instance_v1/private_endpoints.tf, modules/databases/mssql_managed_instance_v1/variables.tf, msssql_managed_instances.tf, msssql_managed_instances_v1.tf
---
Added Private Endpoint feature for Sqlmi module
Run the code in mssqlmi examples folder
=> Add Private Endpoint feature for SQL MI module

modules/logic_app/standard/module.tf
=> fix: adding https_only for logic app standard

.github/workflows/pr_workflow.yaml
=> Remove token access

examples/networking/private_links/endpoints/100-azure-open-ai-private-endpoint/configuration.tfvars, modules/networking/private_links/endpoints/subnet/cognitive_services_account.tf, networking_private_links.tf
=> Added centralized private endpoint for cognitive services account

examples/tests/mock_data/data.tfmock.hcl
Adding the requires stubs and settings for mock tests.
=> Fix mock tests scenarios

modules/networking/private-dns/output.tf
Add outputs for all type of private zone records
---
=> feat(private-dns-outputs): DNS records

cognitive_service.tf, examples/cognitive_services/101-cognitive-services-account-managed-identity/configuration.tfvars, modules/cognitive_services/cognitive_services_account/diagnostics.tf, modules/cognitive_services/cognitive_services_account/main.tf, modules/cognitive_services/cognitive_services_account/output.tf, modules/cognitive_services/cognitive_services_account/private_endpoints.tf, modules/cognitive_services/cognitive_services_account/variables.tf
---
Enhanced cognitive services: private endpoint support, diagnostic settings, more outputs
=>  Enhanced cognitive services: private endpoint support, diagnostic settings, more outputs

.github/workflows/standalone-scenarios.json, eventgrid.tf, examples/cognitive_services/101-cognitive-services-account-managed-identity/configuration.tfvars, examples/messaging/eventgrid/300-simple-eventgrid-system-topic/configuration.tfvars, locals.combined_objects.tf, locals.tf, modules/messaging/eventgrid/eventgrid_system_event_subscription/main.tf, modules/messaging/eventgrid/eventgrid_system_event_subscription/module.tf, modules/messaging/eventgrid/eventgrid_system_event_subscription/output.tf, modules/messaging/eventgrid/eventgrid_system_event_subscription/variables.tf, modules/messaging/eventgrid/eventgrid_system_topic/main.tf, modules/messaging/eventgrid/eventgrid_system_topic/module.tf, modules/messaging/eventgrid/eventgrid_system_topic/output.tf, modules/messaging/eventgrid/eventgrid_system_topic/variables.tf
---
Add support for eventgrid system topics and event subscriptions.
=> Add eventgrid system topics support
