modules/compute/aks/aks.tf, modules/compute/aks/output.tf, networking.tf
Added private_fdqn & node_rg to AKS output.
Support orchestrator_version for Default nodepool
Add remote tfstate in networking module to allow spoke to reference Firewall in hub LZ
azurerm_routes = {
default_to_firewall_rg1 = {
name               = "0-0-0-0-through-firewall-rg1"
resource_group_key = "aks_spoke_rg1"
route_table_key    = "default_to_firewall_rg1"
address_prefix     = "0.0.0.0/0"
next_hop_type      = "VirtualAppliance"
remote_tfstate = {
tfstate_key = "networking_hub"
output_key  = "azurerm_firewalls"
fw_key      = "fw_rg1"
interface_index = 0
}
}
=> Reference remote Firewall in Hub

networking_virtual_wan.tf
Fixes a bug when deploying Virtual WAN landing zone where the index is not defined correctly for local and remote landing zone state. 
```
Error: Invalid index
on /home/vscode/.terraform.cache/modules/networking/networking_virtual_wan.tf line 33, in resource "azurerm_virtual_hub_connection" "vhub_connection":
33:   remote_virtual_network_id = lookup(each.value.vnet, "lz_key", null) == null ? local.combined_objects_networking[each.value.vnet.vnet_key].id : local.combined_objects_networking[each.value.vnet.output_key].vnets[each.value.vnet.vnet_key].id
|----------------
| each.value.vnet.vnet_key is "vnet_re1"
| local.combined_objects_networking is object with 3 attributes
The given key does not identify an element in this collection value.
```
=> Hotfix for Virtual WAN peering index error

modules/diagnostics/module.tf
Update destination type to event_hub
```hcl
diagnostic_profiles = {
vnet = {
definition_key   = "networking_all"
destination_type = "storage"
destination_key  = "all_regions"
}
operations = {
name             = "operations"
definition_key   = "networking_all"
destination_type = "log_analytics"
destination_key  = "east_logs"
}
operationsevh = {
name             = "operationsevh"
definition_key   = "network_security_group"
destination_type = "event_hub"
destination_key  = "central_logs"
}
}
```
=> Update event_hub destination type

modules/diagnostics/module.tf
Removing the try() gives better visibility in the mapping errors that can occur between the structures.
=> Quick fix for Event Hub namespaces diagnostics

modules/networking/application_gateway/variable.tf
Choosing "WAF" as sku_tier results in an error. Removed redundant space in variable validation condition.
=> Removed redundant space in terraform-azurerm-caf/modules/networking/application_gateway/variable.tf

container_registry.tf
For the deployment of azure container groups it is useful to be able to fetch the login_server and possibly the admin_username and admin_password of a container registry
=> Missing module output

.github/workflows/master-100.yaml, .github/workflows/master-standalone.yaml, examples/cosmos_db/100-simple-cosmos-db-cassandra/cassandra.tfvars, examples/cosmos_db/100-simple-cosmos-db-cassandra/standalone/ci.sh, examples/cosmos_db/100-simple-cosmos-db-cassandra/standalone/main.tf, examples/cosmos_db/100-simple-cosmos-db-cassandra/standalone/module.tf, examples/cosmos_db/100-simple-cosmos-db-cassandra/standalone/readme.md, examples/cosmos_db/100-simple-cosmos-db-cassandra/standalone/variables.tf, modules/databases/cosmos_db/cassandra_keyspace.tf, modules/databases/cosmos_db/cassandra_keyspace/cassandra_keyspace.tf, modules/databases/cosmos_db/cassandra_keyspace/main.tf, modules/databases/cosmos_db/cassandra_keyspace/output.tf, modules/databases/cosmos_db/cassandra_keyspace/variables.tf
First draft of Cosmos DB Cassandra API. Terraform only supports creating a Cassandra Keyspace at the moment rather than the sub-resource of a Table; the Go SDK supports this, but Terraform support is not yet available.
=> Cosmos DB Cassandra API

modules/networking/public_ip_addresses/module.tf, modules/networking/public_ip_addresses/variables.tf, networking.tf
This is to set the domain name with the name of the VM automatically. As this name can be dynamically created it can't be set upfront from the TFVARS input file
=> Generate DNS from VM name

modules/security/keyvault/output.tf
=> added back basetags output for keyvault

examples/compute/kubernetes_services/101-single-cluster/aks.tfvars, examples/compute/kubernetes_services/102-multi-nodepools/aks.tfvars, examples/compute/kubernetes_services/103-multi-clusters/aks.tfvars, examples/compute/kubernetes_services/104-private-cluster/aks.tfvars, modules/azuread/applications/module.tf, modules/azuread/groups/group.tf, modules/azuread/groups_members/members.tf, modules/compute/aks/aks.tf, modules/compute/aks/output.tf
Remove Sensitive outputs
Fixed Terraform v 0.15 error with sensitive value
```output
│ Error: Output refers to sensitive values
│
│   on .terraform/modules/caf/modules/compute/aks/output.tf line 39:
│   39: output kube_admin_config_raw {
│
│ Expressions used in outputs can only refer to sensitive values if the sensitive attribute is true.
```
https://github.com/Azure/caf-terraform-landingzones-starter/issues/51
=> Remove sensitive outputs in AKS for Terraform 0.15

.github/workflows/master-100-tf13.yaml, .github/workflows/master-100-tf14.yaml, .github/workflows/master-100-tf15.yaml, .github/workflows/master-standalone-tf13.yaml, .github/workflows/master-standalone-tf14.yaml, .github/workflows/master-standalone-tf15.yaml, examples/managed_service_identity/100-msi-levels/configuration.tfvars, examples/managed_service_identity/100-msi-levels/standalone/ci.sh, examples/managed_service_identity/100-msi-levels/standalone/main.tf, examples/managed_service_identity/100-msi-levels/standalone/module.tf, examples/managed_service_identity/100-msi-levels/standalone/readme.md, examples/managed_service_identity/100-msi-levels/standalone/variables.tf, managed_identities.tf, modules/security/managed_identity/main.tf, modules/security/managed_identity/managed_identity.tf, modules/security/managed_identity/variables.tf
Currently the MSI adds a module tag but does not allow configuration tags to be added to the resource. 
Updated MSI tags module to use and merge local setting tags.
Closes #376
=> Updated MSI tags, added example

examples/storage_accounts/100-simple-storage-account-blob-container/keyvaults.tfvars, examples/storage_accounts/100-simple-storage-account-blob-container/standalone/readme.md, modules/security/keyvault_access_policies/policies.tf
- Updated the Key Vault access policies configuration. dia_storage_account_key  changed to diagnostic_storage_account_key for standardization.
- Updated the readme file with the correct path
=> Updated Key Access Policy configuration name for  diagnostic storage account

modules/networking/firewall_policies/firewall_policy.tf
=> DNS proxy_enabled not processed in Azure firewall policy

locals.tf
Allow for dynamic app settings of SQL Server and DB outputs. 
Example: 
dynamic_app_settings = {
"SQL_SERVER_FQDN" = {
mssql_servers = {
sql_server = {
attribute_key = "fully_qualified_domain_name"
}
}
}
}
=> Add SQL Server and DB to Dynamic App Settings

.github/workflows/master-standalone-tf13.yaml, .github/workflows/master-standalone-tf14.yaml, .github/workflows/master-standalone-tf15.yaml, examples/compute/virtual_machine/106-marketplace-image-with-plan/configuration.tfvars, modules/compute/virtual_machine/vm_linux.tf
- Added 'plan' block for Linux Virtual Machines
- As a prerequisite user needs to accept the license agreements once per subscription for the image. 
For more information - https://docs.microsoft.com/en-us/azure/virtual-machines/windows/cli-ps-findimage#accept-purchase-plan-terms
For this example: 
```
$agreementTerms=Get-AzMarketplaceterms -Publisher "citrix" -Product "netscaler-130-ma-service-agent" -Name "netscaler-ma-service-agent"
Set-AzMarketplaceTerms -Publisher "citrix" -Product "netscaler-130-ma-service-agent" -Name "netscaler-ma-service-agent" -Terms $agreementTerms -Accept
```
=> Added 'plan' block for Linux VMs

modules/azuread/applications/scripts/grant_consent.sh, modules/azuread/roles/scripts/set_ad_role.sh, modules/subscription_billing_role_assignment/billing_role_assignment.tf, modules/subscription_billing_role_assignment/role_assignment/billing_role_assignment.tf, modules/subscription_billing_role_assignment/role_assignment/variables.tf, modules/subscription_billing_role_assignment/variables.tf, modules/subscriptions/scripts/assign_subscription_to_mg.sh, modules/subscriptions/scripts/tags.sh, subscriptions.tf
Update removes hard coded Azure endpoints and replaces them with dynamically retrieved values from 'az cloud show'. 
This is required for working on different clouds such as AzureUSGovernment where these endpoints are different.
=> Updated remaining hardcoded Azure urls

networking.tf
Added additional elements to iterator to allow `lz_key` to be specified inside the `private_ip_keys` structure
before:
```
azurerm_routes = {
name  = {
name = "name"
...
lz_key = "lz_key_name"
private_ip_keys = {
...
```
after:
```
azurerm_routes = {
name  = {
name = "name"
...
private_ip_keys = {
lz_key = "lz_key_name"
...          
```
=> Updated local.combined_objects_azurerm_firewalls each.value iterator

modules/compute/aks/aks.tf
- Convert subnet to accept a dictionary of key/values (landing zone key and subnet key) 
- Also Allow subnets to accept a resource id 
- This refactoring helps decouple the VNET/Subnet creation from the AKS construction set.
Example Usage in your aks config:
```bash
aks_clusters = {
cluster_re1 = {
name               = "aks-sample-cluster"
resource_group_key = "aks_rg"
.......
vnet_key = "vnet"
lz_key   = "swetha_resources" #example landing zone key
default_node_pool = {
name    = "..."
vm_size = "Standard_DS2_v2"
subnet = {
resource_id = "/subscriptions/<subscription-id>/resourceGroups/<resource-group-name>/providers/Microsoft.Network/virtualNetworks/<vnet-id>/subnets/<subnet-id>       
}
....
}
node_pools = {
pool = {
name = "..."
mode = "User"
subnet = {         
lz_key = …
```
=> Refactor aks subnets to take in a dictionary of key(s) and resource id 

examples/networking/virtual_wan/108-vwan-vpn-site/virtual_wan.tfvars, examples/networking/virtual_wan/109-vwan-vpn-gateway-connection/virtual_wan.tfvars, landingzones/caf_example/README.md, landingzones/caf_example/module.tf, landingzones/caf_example/variables.tf, locals.combined_objects.tf, locals.tf, modules/networking/application_gateway/locals.backend_pools.tf, modules/networking/virtual_wan/virtual_hub/site_to_site_gateway.tf, modules/networking/vpn_gateway_connection/main.tf, modules/networking/vpn_gateway_connection/module.tf, modules/networking/vpn_gateway_connection/output.tf, modules/networking/vpn_gateway_connection/variables.tf, modules/networking/vpn_site/main.tf, modules/networking/vpn_site/module.tf, modules/networking/vpn_site/output.tf, modules/networking/vpn_site/variables.tf, networking_vpn_gateway_connection.tf, networking_vpn_site.tf
Adds support for `vpn_sites` and `vpn_gateway_connections`
=> Add support for vpn_sites and vpn_gateway_connections

modules/networking/firewall_policy_rule_collection_groups/firewall_policy_rule_collection_groups.tf, modules/networking/firewall_policy_rule_collection_groups/variables.tf, networking_firewall.tf
This PR add support to create an azurerm_firewall_policy_rule_collection_group and attach it to a remote firewall policy
=> Add remote firewall policy to rule_collection_groups

networking_virtual_hub_connection.tf
Referring to the issue in [here](https://github.com/aztfmod/terraform-azurerm-caf/issues/576)
Fixing to ensure output variable match between landingzones and aztfomd.
=> Fix vhub connection outputs name

examples/app_gateway/100-simple-app-gateway/application.tfvars, modules/networking/application_gateway/application_gateway.tf, modules/networking/application_gateway/locals.tf
Addresses issue #432,  #557
Example
Specifying the health probe(s).
```hcl
application_gateway_applications = {
aspnetapp_az1_agw1 = {
name                    = "apim"
application_gateway_key = "agw1"
listeners ...
probes = {
probe_1 = {
name                = "probe-apim-443"
protocol            = "Https"
path                = "/status-0123456789abcdef"
host                = "someserver-apim.azure-api.net"
interval            = 30
timeout             = 30
unhealthy_threshold = 3
match               = {
status_code = ["200-399"]
}
}
}
}
}
```
Specifying the health probe assignment for the backend setting. Note: the use of probe_key which refers to the key of the previous configured probe for the given app gateway application.
```hcl
backend_http_setting = {
port …
```
=> added support for configuring application gateway health probes and assigning to backend settings

examples/compute/kubernetes_services/103-multi-clusters/aks.tfvars, examples/compute/kubernetes_services/103-multi-clusters/networking.tfvars, examples/compute/kubernetes_services/104-private-cluster/acr.tfvars, examples/compute/kubernetes_services/104-private-cluster/aks.tfvars, examples/compute/kubernetes_services/104-private-cluster/configuration.tfvars, examples/compute/kubernetes_services/104-private-cluster/diagnostics.tfvars, examples/compute/kubernetes_services/104-private-cluster/networking.tfvars, examples/compute/kubernetes_services/104-private-cluster/vm.tfvars
1. **Example - 103-multi-clusters**
- Fix the resource group keys and unused lz_keys in the kubernetes multi-clusters examples
2. **Example - 104-private-cluster**
- Add the missing storage account diagnostics and resource group
- Remove unused vnet and peering
- Fix the incorrect/unused landing zone keys
Issue:  https://github.com/aztfmod/terraform-azurerm-caf/issues/595
- Tested all the examples locally by running terraform plan, apply and destroy. All examples now succeed.
=> Fix the bugs in AKS specific examples

aks_clusters.tf, examples/compute/kubernetes_services/105-cluster-usermsi/aks.tfvars, examples/compute/kubernetes_services/105-cluster-usermsi/diagnostics.tfvars, examples/compute/kubernetes_services/105-cluster-usermsi/networking.tfvars, modules/compute/aks/aks.tf, modules/compute/aks/variables.tf
- Add support for a creating an AKS cluster using user managed identity
- Add an example `105-cluster-usermsi` to demonstrate how to use this feature.
- This feature is needed in order to register the cluster against a private dns zone: (See note in terraform registry -  https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#private_dns_zone_id)
- Locally tested the example (with user assigned identity) using terraform commands 
- Both terraform plan and apply succeeded.
=> Add support for a creating an AKS cluster using user managed identity

.github/workflows/master-standalone-tf100.yaml
Now that we have README files in `examples/<module-name>/README.md`, it is better to have the CI ignore those changes to save on CI hours and free up the queue for other developers
=> ci/ignore all README file updates

examples/app_gateway/101-private-public/application.tfvars, examples/app_gateway/101-private-public/application_gateways.tfvars, modules/networking/application_gateway/application_gateway.tf, modules/networking/application_gateway/locals.tf
This PR provides support for configuring rewrite rule sets against an application gateway
Included in the changes is an example of how to apply rule sets at different levels of the application gateway configuration.
=> Support for application gateway rewrite rule sets

modules/networking/virtual_hub_route_tables/route_local.tf, modules/networking/virtual_hub_route_tables/variables.tf, networking_virtual_hub_route_table.tf
Add additional support to allow referencing remote firewall resource ID when secure vhub are used. 
Adding resources from `networking_virtual_hub_route_table.tf` might cause confusion when the merge state include both `var.remote_objects.virtual_hub_connections` and `var.remote_objects.azurerm_firewalls`. 
Might have multiple route block defined in `modules/networking/virtual_hub_route_tables/route_local.tf`, each of them may reference to its own landing zone, using the module inside might be more accurate.
Hence decided to use the inner module by passing in `var.emote_objects` into module.
=> Update to support more resource reference in RT nexthop

examples/storage_accounts/104-file-share-with-backup/configuration.tfvars, examples/storage_accounts/104-file-share-with-backup/fileA, examples/storage_accounts/104-file-share-with-backup/fileB, examples/storage_accounts/104-file-share-with-backup/fileC, modules/storage_account/file_share/share_file.tf, modules/storage_account/file_share_file/file.tf, modules/storage_account/file_share_file/output.tf, modules/storage_account/file_share_file/variables.tf
Currently, users can create directories in in storage shares using CAF but not [files](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_share_file). This code will allow those files, using either a relative or absolute path.
=> Storage - Add files to storage shares

examples/compute/virtual_machine/100-single-linux-vm/configuration.tfvars, modules/compute/virtual_machine/vm_linux.tf
Currently, the linux VM's custom data can only be passed in as a file. This will allow text to be added. Perhaps in the future a `locals` object will be created to allow variables such as `storage_account_key` to be passed into the `custom_data`.
=> Custom Data - Allow Txt for `custom_data` on linux vm creation

examples/storage_accounts/100-simple-storage-account-blob-container/configuration.tfvars, managed_identities.tf, storage_accounts.tf, virtual_machines.tf
Current Storage account only can use the RG that is created within the same tfstate only. Adding support for remote lz_key and key in order to be able to deploy to remote RG if required.
=> Support remote rg lz referencing

examples/networking/private_dns_vnet_link/100_pvtdns_vnetlink/configuration.tfvars, locals.tf, modules/networking/private_dns_vnet_link/main.tf, modules/networking/private_dns_vnet_link/module.tf, modules/networking/private_dns_vnet_link/output.tf, modules/networking/private_dns_vnet_link/variables.tf, networking_private_dns.tf
- Add a sub-module for creating virtual-network-links in a separate landing zone and not as part of private-dns-zone creation
- Sometime private-dns-zones and vnets are not created together in the same even landing zone or even same level. Separating the vnet-link module would enable users to create vnet-links in a separate lz linking the dependencies
- This requires changes in https://github.com/Azure/caf-terraform-landingzones repository. PR to merged for these changes to work: https://github.com/Azure/caf-terraform-landingzones/pull/251
- Added a sample config tfvars file to  showcase the usage
=> Add support for adding virtual-network-links outside of private-dns-zone creation

examples/networking/firewall/103-firewall-policies/configuration.tfvars, modules/networking/firewall_policies/firewall_policy.tf
Add IDS block in firewall policies to enable defining the Azure Firewall Policies in code.
=> Support IDS in policy

examples/networking/virtual_network/100-simple-vnet-subnets-nsgs/configuration.tfvars, networking.tf
should be using `var.remote_objects.azurerm_firewalls` instead of `var.remote_objects.azurerm_firewall`. updated and tested with example.
=> Fix typo azurermfw vnet

examples/mysql_server/102-private-endpoint-mysql/configuration.tfvars, mssql_servers.tf, msssql_managed_instances.tf, mysql_servers.tf
Allow reference to remote lz to use the keyvault centrally or specifically outside out the creation of sql.
=> Support remote KeyVault for MSSQL or MySQL

examples/compute/virtual_machine/108-single-linux-storage-connect-custom-data/configuration.tfvars, modules/compute/virtual_machine/variables.tf, modules/compute/virtual_machine/vm_linux.tf, modules/storage_account/file_share/output.tf, modules/storage_account/file_share_directory/output.tf, modules/storage_account/output.tf, virtual_machines.tf
Currently, users have the ability to add `custom_data` to a Linux VM in two ways:
1. Passing a local path to a script.
2. Directly inserting code in the `tfvars`
This allows users to manually enter `custom_data` for these machines. But it does __not__ allow users to dynamically build a string for the `custom_data` from Terraform outputs.
In our use case, we need to set the following string as the `custom_data`, assuming a storage account, file share, and directory exist.:
```
storage-account=stname, access-key=some-secret, file-share=myfileshare, share-directory=testdirectory
```
The implementation I propose is to use a locals block that contains a map called `dynamic_custom_data`. Here, any developer would be able to add their condition. The key would be used to reference their …
=> Create a `custom_data` string with Terraform Ouputs

examples/compute/virtual_machine/109-legacy-vm-creation/configuration.tfvars, modules/compute/virtual_machine/main.tf, modules/compute/virtual_machine/vm_legacy.tf, modules/compute/virtual_machine/vm_linux.tf, modules/compute/virtual_machine/vm_windows.tf, modules/compute/virtual_machine/vm_windows_winrm_self.tf
This PR will capture the old vm creation module.
=> Allow legacy method for VM creation with data disk at boot time

modules/compute/virtual_machine/mssql_vm.tf
Added a depends_on block for mssql_vm as the storage configuration fails if the data disk attachment has not been completed
=> mssql_vm depends_on vm data disk

locals.combined_objects.tf, networking.tf
Currently, you are unable to attach a DDoS protection plan to a vNet in a different LZ to that of the DDoS protection plan, this PR corrects that.
https://github.com/aztfmod/terraform-azurerm-caf/issues/775
=> Enable DDOS plan from other LZs

modules/security/keyvault_certificate_request/global_sign.tf
Added lifecycle ignore_changes to ignore triggers for preventing renewed SSL certificates from being reverted.
=> Added lifecycle ignore_changes to global_sign.tf

examples/networking/private_links/endpoints/centralized/private_endpoints.tfvars, modules/networking/private_endpoint/private_endpoint.tf, networking_private_links.tf
Add support to reference DNS by resource IDs (see examples/networking/private_links/endpoints/centralized
Add support for new resources (aks_clusters, application_gateways, ACR, cosmos_dbs, data_factory, event_hub_namespaces, machine_learning, postgresql and synapse
=> Add private dns ids + resources

marketplace.tf, modules/compute/aks/aks.tf
Bug: 
If Private DNS zone ID is added, AKS is being destroyed and recreated. Private_dns_zone_id is an optional parameter and should not force the cluster to recreate as per [tf registry](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#private_dns_zone_id)
```
+/- resource "azurerm_kubernetes_cluster" "aks" {
- api_server_authorized_ip_ranges     = [] -> null
- enable_pod_security_policy          = false -> null
+ fqdn                                = (known after apply)
~ id                                  = "/subscriptions/*/resourcegroups/rg-**-001/providers/Microsoft.ContainerService/managedClusters/private-akscluster" -> (known after apply)
~ kube_admin_config                   = [] -> (known after apply)
+ kube_admin_config_raw …
```
=> AKS - Private DNS causes cluster to redeploy

modules/compute/virtual_machine_scale_set/main.tf, modules/compute/virtual_machine_scale_set/vmss_windows.tf
Fixed bug: Making the virtual machine scale set nic member of an application security group defined in another landingzone always failed
Added timezone and license_type attributes to the windows vmss
=> Remote ASG in VMSS, added timezone, license_type to windows vmss

examples/compute/virtual_machine/110-single-windows-vm-custom-script-extension/configuration.tfvars, examples/compute/virtual_machine/110-single-windows-vm-custom-script-extension/helloworld.ps1, examples/vm_extensions.tf, modules/compute/virtual_machine_extensions/custom_script.tf, modules/compute/virtual_machine_extensions/variables.tf
Added virtual machine custom script extension according to #514
Module supports using managed or system identity for downloading files https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-windows
Follow up to https://github.com/aztfmod/terraform-azurerm-caf/pull/740:
- Added ability to reference storage account for fileuris by using key/landing zone key
- Added example
storageaccountname and storageaccountkey attributes are not implemented
=> Adding virtual machine custom script extension 

modules/compute/virtual_machine/vm_windows_winrm_self.tf
there is limit of 15 tags in kv cert and when there's more than 15 tags, error below shows up 
│ Error: keyvault.BaseClient#CreateCertificate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadParameter" Message="Property has invalid value\r\n"
=> remove inherited tags into winrm self-signed cert

modules/security/keyvault_certificate/certificate.tf
kv cert only support up to 15 tags, beyond that will gives badparameter 400 error
=> remove inherited tags on kv cert

aks_clusters.tf, modules/compute/aks/aks.tf
1.  When trying to provision an AKS cluster with an exisitng vnet/subnet through a resource id, I ran into the following error:
```
> │ Error: Unsupported attribute
> │ 
> │   on /aks_clusters.tf line 16, in module "aks_clusters":
> │   16:   subnets             = lookup(each.value, "lz_key", null) == null ? local.combined_objects_networking[local.client_config.landingzone_key][each.value.vnet_key].subnets : local.combined_objects_networking[each.value.lz_key][each.value.vnet_key].subnets
> │     ├────────────────
> │     │ each.value is object with 11 attributes
> │ 
> │ This object does not have an attribute named "vnet_key".
```
From what I understand, the current logic in aks_clusters.tf attempts to seek the `subnets` information through the `vnet_key`. 
In the case of an existing …
=> Make subnets attribute optional in AKS and to fix service_cidr error

modules/networking/private-dns/virtual_network_link.tf
Private dns vnet link has no option to specify a remote virtual network id.
=> Private dns vnet link - Added support to reference remote vnet

.github/workflows/standalone-scenarios.json, examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/configuration.tfvars, examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/scripts/helloworld.ps1, examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/scripts/helloworld.sh, examples/compute/virtual_machine_scale_set/103-linux-win-vmss-domain-join-extension/configuration.tfvars, examples/vmss_extensions.tf, modules/compute/virtual_machine_scale_set_extensions/custom_script.tf, modules/compute/virtual_machine_scale_set_extensions/domain_join.tf, modules/compute/virtual_machine_scale_set_extensions/variables.tf
Related to [PR 278](https://github.com/Azure/caf-terraform-landingzones/pull/278) in [caf-terraform-landingzones](https://github.com/Azure/caf-terraform-landingzones).
Local plan succeeded using the following commands:
```
cd examples/vmss_extensions.tf.
terraform plan -var-file compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/configuration.tfvars
```
Custom script extension example included, but no domain join example yet.
=> Add support for vmss custom script and domain join extensions

modules/networking/load_balancers/load_balancers.tf
1. To allow the LB's frontend_ip_configurations to support the referencing of existing subnet through resource id
2. Support for the referencing of existing vnet through resource id, for the LB's backend_address_pool
=> Inject preexisting vnet_id for load balancer

modules/compute/virtual_machine_scale_set/vmss_linux.tf
This PR gives the user the ability to specify an admin password only if disable_password_authentication is set to false. This matches the feature we have for vm_linux
=> Allow admin password in VMSS

modules/compute/virtual_machine/mssql_vm.tf, modules/compute/virtual_machine/vm_disk.tf
Added option to replace disk attachment to restored data disk.
data_disks = {
db_data1 = {
// restored_disk_id     = "" // the restored disk id will be added here for attachment
name                 = "testdatadisk"
storage_account_type = "Standard_LRS"
create_option = "Empty"
disk_size_gb  = "10"
lun           = 1
}
}
=> Data Disk restore interim fix

container_groups.tf, examples/compute/container_groups/102-aci-private-registry/container_groups.tfvars, examples/compute/container_groups/102-aci-private-registry/global_settings.tfvars, examples/compute/container_groups/102-aci-private-registry/keyvaults.tfvars, examples/compute/container_groups/102-aci-private-registry/managed_identities.tfvars, examples/compute/container_groups/102-aci-private-registry/resource_groups.tfvars, modules/compute/container_group/container_group.tf, modules/compute/container_group/variables.tf
Updated container groups to now support image_registry_credentials.
A example is provided using dynamic_keyvault_secrets as as credential source.
=> Added support for image_registry_credentials to container groups

modules/compute/virtual_machine_scale_set/vmss_windows.tf
The [settings](https://github.com/aztfmod/terraform-azurerm-caf/blob/master/modules/compute/virtual_machine_scale_set/vmss_windows.tf#L183) value of [extensions](https://github.com/aztfmod/terraform-azurerm-caf/blob/master/modules/compute/virtual_machine_scale_set/vmss_windows.tf#L171) requires a string instead of a map to make the configuration below functional.
``` hcl
extensions = {
microsoft_azure_health_extension = {
name                       = "HealthExtension"
publisher                  = "Microsoft.ManagedServices"
type                       = "ApplicationHealthWindows"
type_handler_version       = "1.0"
auto_upgrade_minor_version = "true"
settings = {
protocol    = "http"
port        = "80"
requestPath = "/"
}
}
}
```
The error below will occur once the `jsonencode()` function …
=> Add jsonencode to convert settings value to string

modules/databases/mssql_database/database.tf
Added Lifecycle to MSSQL Databases to prevent redeploy on addition of new SQL Servers.
=> MSSQL Redeploy on adding new SQL Server

modules/monitoring/monitor_autoscale_settings/monitor_autoscale_settings.tf
This PR further improves the autoscale module. The module now allows you to exclude the 'rule' and 'notification' blocks, along with a few other improvements to improve the readability of the code.
=> Conditional improvements to autoscale module

modules/compute/virtual_machine/mssql_vm.tf
Condition in the data block is not working, removed to fix this null error
=> Fix: Missing parameter sql_username_key causing error

.pre-commit-config.yaml, examples/networking/route_server/100-simple-route-server/configuration.tfvars, modules/networking/virtual_wan/virtual_hub/variables.tf, modules/networking/virtual_wan/virtual_hub/virtual_hub.tf, networking_virtual_hubs.tf
Azure Route Server is actually a standalone Virtual Hub.
Creating a Route Server requires to create a virtual hub with a standard sku, no (null) virtual wan and no address prefix.
This PR is a minor fix on virtual hub module to allow the creation of a route server. It also implements an example.
This should solve #477 .
=> Add Azure Route Server compatibility

azurerm_application_insights.tf, diagnostics.tf, modules/compute/container_registry/private_endpoint.tf, modules/databases/mssql_server/private_endpoints.tf, mssql_servers.tf, networking.tf, virtual_machines_scale_sets.tf
Encountered the following issues while provisioning a Virtual Machine Scale Set that references a remote resource group:
Tried implementing an enhancement which will search for the landing zone of remote resource group via the `lz_key` attribute, followed by the resource group key in that landing zone via the `key` attribute. This would take precedence before searching for any local resource group via the `resource_group_key` attribute.
This was also applied across Azure Application Insights, MSSQL Server and Azure Container Registry.
=> Fix remote resources composition bug for VMSS, MSSQL and networking

.github/workflows/standalone-scenarios.json, examples/keyvault/104-keyvault-dynamic-secret/README.md, examples/keyvault/104-keyvault-dynamic-secret/configuration.tfvars, modules/security/dynamic_keyvault_secrets/keyvault.tf, modules/security/dynamic_keyvault_secrets/secret_dynamic/keyvault_secret.tf, modules/security/dynamic_keyvault_secrets/secret_dynamic/variables.tf
this new feature allows the users to create a new random dynamic password as a secret directly by adding the value of the secret equal to "dynamic" and adding a new config object to send the configurations of the new password.
=> add dynamic value to dynamic kv secret

modules/networking/private_endpoint/private_endpoint.tf
It's done correctly [here](https://github.com/aztfmod/terraform-azurerm-caf/blob/main/modules/networking/private_links/endpoints/private_endpoint/private_endpoint.tf#L29-L49), so bringing this module in line with that
=> Add missing value iterator in dynamic private_dns_zone_group block

cosmosdb_sql_databases.tf, locals.combined_objects.tf, locals.tf, modules/databases/cosmos_dbs/output.tf, modules/databases/cosmos_dbs/sql_database/output.tf
A separate module allows the cosmos account to be defined in a different
landing zone to the database. For example you could define a shared cosmos
db account with a private endpoint in level 3 and project-specific sql
databases inside that account in level 4 landing zones. This allows you to
nicely separate shared and project components.
=> Add cosmosdb_sql_databases module

api_management.tf, examples/apim/115-api_management_private_virtual_network/configuration.tfvars, modules/apim/api_management/module.tf, modules/apim/api_management/variables.tf
This PR attempts to fix the bug with the ```virtual_network_configuration``` block by declaring the ```vnets``` variable and also resolving to proper subnet id.
=> Fix APIM private virtual_network_configuration block

azuread_roles.tf
this will fix issue: https://github.com/aztfmod/terraform-azurerm-caf/issues/1026
**Limitations**: Assigning AAD roles to AAD groups works only with _AAD Premium_ functionality **enabled**.
=> Enable AAD role assignment for AAD security groups

modules/databases/mariadb_server/server.tf, modules/databases/mysql_server/server.tf, modules/databases/postgresql_server/server.tf
Fix #1015 (Flexible servers do not need login name secret)
=> Add additional secrets for database resources  (mariadb, mysql, postgres)

examples/networking/dns_zones/100-simple-dns_zone/dns_zone_records.tfvars, modules/networking/dns_zone/records/record_a.tf, modules/networking/dns_zone/records/record_aaaa.tf, modules/networking/dns_zone/records/record_cname.tf
---
DNS records of type alias using resource_id reference was hard coded with ttl = 300, probably becauce of some earlier limitation. Custom ttl, example ttl = 1 is confirmed to work with dns records of type alias now.
Expanded existing exampl configuration for "networking/dns_zones/100-simple-dns_zone" with example_alias record with ttl=1, allready part of standalone-scenario.json.
=> Add TTL property to all records

modules/networking/application_gateway_application/http_settings.tf, modules/networking/application_gateway_application/scripts/set_resource.sh
---
Environment variable used for override backend path setting collides with unix system PATH variable. Renamed the environment variable.
=> Rename override backend path environment variable

roles.tf
This change allows role assignments to Log Analytics within current landing zone
- [ X] NO
log_analytics = {
test = {
region             = "region1"
name               = "test-law"
resource_group_key = "management"
}
}
role_mapping = {
built_in_role_mapping = {
log_analytics = { # <-- scope_resource_key
test = {
"Log Analytics Contributor" = {
azuread_groups = {
lz_key = "launchpad"
keys = [
"connectivity",
]
}
}
}
}
}
=> Add role assignments for Log Analytics

modules/webapps/appservice/main.tf, modules/webapps/appservice/storage_account.tf
Application logging & web server logging is already accommodated for in https://github.com/aztfmod/terraform-azurerm-caf/blob/main/modules/webapps/appservice/module.tf, however it requires sas_url for the storage container. This can be dynamically obtained similar to the backup container approach (which is not accommodated for)
=> Enable application logging & web server logging storage container sas url to be dynamically obtained

examples/webapps/appservice/109-appservice-appgw/configuration.tfvars, modules/webapps/appservice/module.tf
---
IP restriction could be set via IP Adress or Service Tag or Subnet ID, so Subnet ID has also to be optional. 
```
module.azure.random_string.prefix[0]: Refreshing state... [id=shgm]
module.azure.module.resource_groups["webapp_appgw"].azurecaf_name.rg: Refreshing state... [id=ekojyhoctennqcqe]
module.azure.module.app_service_plans["asp_webapp_appgw"].azurecaf_name.plan: Refreshing state... [id=himyqetuvwsxcjcv]
module.azure.azurecaf_name.public_ip_addresses["pip_appgw"]: Refreshing state... [id=ubpyqnpokmtxcljn]
module.azure.module.resource_groups["webapp_appgw"].azurerm_resource_group.rg: Refreshing state... [id=/subscriptions/9f6c4025-c3e6-4d11-910a-572becb77452/resourceGroups/module-test-rg-webapp-appgw]
module.azure.module.networking["webapp_appgw"].module.subnets["appgw"].azurecaf_ …
```
=> Subnet ID has to be optional for App Service

modules/webapps/appservice/module.tf, modules/webapps/appservice/slot.tf
---
When using a managed identity with a slot, the code differed from the main module. The fix I've introduced is a direct copy from the main module code to the slot module. This fixes this bug.
added support for `key_vault_reference_identity_id `. 
Using a user-assigned managed identity to retrieve keyvault secrets is now enabled.
Add the following to the `webapp.tfvars`:
```
settings = {
enabled = true
key_vault_reference_identity = {
key = "managed_identity_key"
}
}
slots = {
staging = {
name = "staging"
identity = {
type = "UserAssigned"
identity_ids = ["managed_identity_key"]
}
}
}
```
=> Add support for key_vault_reference_identity_id with MSI for App Service

modules/compute/virtual_machine_scale_set/output.tf, modules/compute/virtual_machine_scale_set/vmss_linux.tf
To be able to use virtual machine scale sets that are autoscaled by a third party (e.g. to be used with Azure DevOps scale set agents https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops ), we need to have to ignore changes to the instances argument as stated in the azurerm documentation:
```
[instances](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine_scale_set#instances) - (Required) The number of Virtual Machines in the Scale Set.
NOTE:
If you're using AutoScaling, you may wish to use [Terraform's ignore_changes functionality](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) to ignore changes to this field.
``` …
=> Add support for autoscaled VMSS

modules/compute/virtual_machine/vm_legacy.tf
changed to `try(each.value.image_uri.publisher, null)`
---
Fixes issues when Market place image has a predefined OS + Data disk.
=> Update image_uri for legacy VM creation method

examples/compute/virtual_machine_scale_set/107-linux-win-vmss-application-health-extension/configuration.tfvars, modules/compute/virtual_machine_scale_set_extensions/application_health.tf, virtual_machines_scale_sets_extensions.tf
This PR adds the application health extension with the help of the [azurerm_virtual_machine_scale_set_extension](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine_scale_set_extension) resource. Related to: https://github.com/Azure/caf-terraform-landingzones/pull/326
=> Add virtual machine scale set application health extension

data_factory.tf, examples/data_factory/117-data_factory_diagnostics/configuration.tfvars, modules/data_factory/data_factory/diagnostics.tf, modules/data_factory/data_factory/variables.tf
---
- [ Yes] I have added example(s) inside the [./examples/] folder
- [ Yes] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [ Yes] I have checked to ensure there aren't other open Pull Requests for the same update/change?
Extends the data factory module to enable defining diagnostic profiles inline with the data factory resource definition.
- [ X] NO
=> Adds support for defining diagnostic profiles to the data factory module

modules/networking/front_door_waf_policy/waf_policy.tf
---
This change will fix missing custom_block_response_body fallback and make custom_rule/managed_rule optional instead of required.
=> Bugfix add missing custom_block_response_body fallback

data_factory.tf, modules/data_factory/data_factory/private_endpoints.tf
---
- [ Yes ] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [ Yes ] I have checked to ensure there aren't other open Pull Requests for the same update/change?
Passing local.resource_groups at root data_factory module prevents downstream selection of remote landing zone (and also causes downstream logic depending on lz_key / landingzone_key to fail).  
At root data_factory module:
- Pass local.combined_objects_resource_groups as remote object vs local.resource_groups
At modules/data_factory/data_factory/private_endpoint:
- Set target resource group name for private endpoint based on lz_key & resource group key
- [ X ] NO
=> fixes remote lz logic w/ private endpoint resource groups

azuread_groups.tf, examples/azuread/104-azuread-group-membership/configuration.tfvars
---
This code change allows you to add a service principal to a group in a different landingzone.
Before the code change using the example config, the code used to fail:
Now it succeeds.
=> Make azuread_groups_membership module landingzone aware

modules/databases/mssql_managed_instance/managed_instance.tf
---
The `Microsoft.KeyVault/vaults/secrets` resource contains credential that won't be returned in response, to suppress that diff, it's recommended to use `ignore_missing_property = true`
=> use `ignore_missing_property` to suppress diff

.devcontainer/docker-compose.yml, .github/workflows/standalone-regressor-tf100.yaml, .github/workflows/standalone-regressor-tf15.yaml, .github/workflows/standalone-tf100.yaml, .github/workflows/standalone-tf15.yaml, modules/azuread/applications/scripts/grant_consent.sh, modules/azuread/service_principal/scripts/grant_consent.sh, modules/compute/aks/scripts/grant_consent.sh
=> Replace objectId with id for az cli 2.37

aks_clusters.tf, modules/compute/aks/aks.tf, modules/compute/aks/variables.tf
---
Evaluation is moved inside the module, now adding and additional subnet does not cause ads recreation.
=> #1190 fix subnet_id evaluation for aks

modules/compute/virtual_machine/vm_linux.tf, modules/compute/virtual_machine/vm_windows.tf
---
Simple change which adds the optional encyrption_at_host_enabled parameter to the existing Azure Windows VM Module. This is now supported within the azurerm terraform provider: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine#encryption_at_host_enabled
=> Add optional encryption_at_host_enabled value

automations.tf, examples/automation/101-automation-account-linked/configuration.tfvars, examples/module.tf, examples/variables.tf, local.remote_objects.tf, locals.combined_objects.tf, locals.tf, modules/automation_log_analytics_links/module.tf, modules/automation_log_analytics_links/output.tf, modules/automation_log_analytics_links/variables.tf
=> Add support for azurerm_log_analytics_linked_service to link automation account and log analytics workspace

examples/module.tf, examples/subscriptions/101-resource-provider-registration/configuration.tfvars, resource_provider_registration.tf, variables.tf
---
This PR adds the Terraform [azurerm_resource_provider_registration](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/resource_provider_registration) resource.
It includes examples for two features to enable, could be expand with more feature examples.
=> Add resource provider registration resource

examples/compute/virtual_machine/110-win-linuxvm-custom-script-extension/configuration.tfvars, modules/compute/virtual_machine_extensions/custom_script.tf, modules/compute/virtual_machine_scale_set_extensions/custom_script.tf
This PR will fix the custom script timestamp in vm and vmss custom scripts
---
- [] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
=> Fix vm and vmss custom script timestamp

examples/azuread/103-service-principal-only/configuration.tfvars, modules/azuread/service_principal/module.tf
This PR adds the attribute "tags" to the resource
azuread_service_principal in the azuread/service_principal module.
---
This PR adds the ability to specify the tags attribute when deploying a azuread_service_principal resource.
=> Add tags attribute to azuread_service_principal

examples/data_explorer/101-kusto_clusters_basic/configuration.tfvars, modules/databases/data_explorer/kusto_clusters/module.tf
The Data Explorer has a configuration Auto Stop Cluster, which is activated by default.  This attribute is only available from AzureRM 2.96.0, since the last update we are on 2.99.0.
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kusto_cluster#auto_stop_enabled
---
=> Add auto_stop_enabled parameter

examples/compute/kubernetes_services/101-single-cluster/aks.tfvars, modules/compute/aks/aks.tf
Seems there is an issue with key_vault_secrets_provider in AKS:
It tries to interate over each parameter in map not over the map itself:
```
╷
│ Error: Too many key_vault_secrets_provider blocks
│ 
│   on ../modules/compute/aks/aks.tf line 184, in resource "azurerm_kubernetes_cluster" "aks":
│  184:     content {
│ 
│ No more than 1 "key_vault_secrets_provider" blocks are allowed
╵
╷
│ Error: Unsupported attribute
│ 
│   on ../modules/compute/aks/aks.tf line 185, in resource "azurerm_kubernetes_cluster" "aks":
│  185:       secret_rotation_enabled  = key_vault_secrets_provider.value.secret_rotation_enabled
│     ├────────────────
│     │ key_vault_secrets_provider.value is "true"
│ 
│ Can't access attributes on a primitive-typed value (string).
╵
╷
│ Error: Unsupported attribute
│ 
│   on …
```
=> Bugfix key_vault_secrets_provider in aks

modules/compute/container_group/container_group.tf, modules/webapps/function_app/output.tf
---
Add the below to a `configuration.tfvars` instance:
```
container_groups = {
aci_dns = {
name               = "aci_dns"
region             = "region1"
resource_group_key = "dns"
ip_address_type    = "Private"
os_type            = "Linux"
network_profile = {
key = "aci_dns"
}
containers = {
coredns = {
name   = "dns-forwarder"
image  = "coredns/coredns:1.9.0"
cpu    = "2"
memory = "2"
commands = ["/coredns", "-conf", "/app/conf/Corefile"]
volume = {
dnscfg = {
name       = "dns-forwarder-conf"
mount_path = "/app/conf"
read_only  = true
secret     = {
Corefile = "xxx"
}
}
}
ports = {
1 = {
port     = 53
protocol = "UDP"
}
}
}
}
}
}
```
=> Container Group Volumes - unsupported attribute

examples/compute/virtual_machine_scale_set/100-linux-win-vmss-lb/configuration.tfvars, examples/compute/virtual_machine_scale_set/101-linux-win-vmss-agw/configuration.tfvars, examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/configuration.tfvars, examples/compute/virtual_machine_scale_set/103-linux-win-vmss-domain-join-extension/configuration.tfvars, examples/compute/virtual_machine_scale_set/104-linux-win-vmss-as-lb/configuration.tfvars, examples/compute/virtual_machine_scale_set/105-linux-win-vmss-autorepair/configuration.tfvars, modules/compute/virtual_machine_scale_set/vmss_linux.tf, modules/compute/virtual_machine_scale_set/vmss_windows.tf, virtual_machines_scale_sets.tf
Add the ability to enable boot diagnostics to a virtual machine _scale set_ with a managed storage account.
Similar to how it's done in the virtual machine [code](https://github.com/aztfmod/terraform-azurerm-caf/blob/main/modules/compute/virtual_machine/vm_windows.tf#L128-L134).
=> Azure managed boot diagnostics on vmss

examples/networking/virtual_network_gateway/104-vpn-point-to-site-gateway/configuration.tfvars, modules/networking/virtual_network_gateways/module.tf
- Adjust P2S VPNGW sample, add related block
---
Fixes the need to have the custom_route block available in the virtual_network_gateway_module
Nothing special
=> -Enhance virtual_network_gateway module add custom_route argument

modules/azuread/groups/group.tf
---
The existing examples already document this feature, there was just no implementation for it:
[azuread/104-azuread-group-membership/configuration.tfvars](https://github.com/aztfmod/terraform-azurerm-caf/blob/main/examples/azuread/104-azuread-group-membership/configuration.tfvars)  
```
owners = {
user_principal_names = []
}
```
The /[azuread](https://github.com/aztfmod/terraform-azurerm-caf/tree/main/modules/azuread)/[groups](https://github.com/aztfmod/terraform-azurerm-caf/tree/main/modules/azuread/groups) module only supports owners via object id.
For my use case it would be nice to be able to reference user principal names instead.
the old interface is left untouched
used this example to test the module:
```
group_key = {
name                   = "group-name"
description …
```
=> adding the option to add owners to groups by user_principal_name

modules/networking/firewall/module.tf
---
Since the subnet attribute is optional ([docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall#subnet_id)), the logic wasn't considering someone not providing it when adding new public IPs to the Firewall.
This change will allow `null` for the subnet_id  (or subnet_key) attribute.
=> [FIX] Make public IP subnet optional

examples/app_gateway/103-public-only/application.tfvars, examples/app_gateway/103-public-only/configuration.tfvars, examples/app_gateway/103-public-only/network_security_group_definition.tfvars, modules/networking/application_gateway/locals.networking.tf
---
- [] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
The parameter `private_ip_address` is optional in AzureRM 2.99.0, however, it's a mandatory parameter in CAF Module 5.6.0.
Just doing a `terraform plan` using the config example in #1280
=> Making private_ip_address optional in AGW following AzureRM 2.99.0

modules/recovery_vault/backup_policies_file_share.tf
:
In recovery_vaults / asr / fs / backup_policies configuration,  weekly/monthly/yearly retention parameters are missing. 
These parameters are present for VM backup policies. So this fix is actually just a copy/paste of this VM parameters into FS ressource
---
The 3 parameters was succesfully applied to a file share backup policy
=> Add weekly/monthly/yearly parameters in fileshare backup retention policy

modules/databases/mssql_server/server.tf
---
The current implementation is creating dynamic configuration based on a optional attribute ([doc](https://registry.terraform.io/providers/hashicorp/azurerm/2.99.0/docs/resources/mssql_server#azuread_authentication_only)).
This PR allow assigning AzureAD administrator to a SQL Server without enforcing usage of "Active Directory Only" users.
=> Fix logic for MSSQL Server AzureAD administrator

modules/data_factory/data_factory_integration_runtime_azure_ssis/module.tf
---
Data Factory Integration Runtime Azure SSIS' "vnet_integration" dynamic block requires all four attributes to be passed, however Terraform permits all four as optional.
Additionally, Terraform states that only "subnet_id" or "subnet_name" can be specified - not both.
This PR allows all four attributes to be optional rather than forced - allowing the resource to be deployed successfully.
=> Data Factory: Add try to vnet integration block

examples/mysql_server/101-vnet-rule-mysql/configuration.tfvars, modules/databases/mysql_server/network_rule.tf
---
- [] I have checked to ensure there aren't other open Pull Requests for the same update/change?
Currently it is not possible to create multiple mysql vnet rules with different subnets. The  mysql_vnet_rules block is using vnet and subnet reference from the top mysql server parameters. This change allows to create multipl vnet rules with different subnets
=> Add support for multiple mysql vnet rules

examples/storage_accounts/100-simple-storage-account-diagnostics/diagnostics.tfvars, examples/storage_accounts/100-simple-storage-account-diagnostics/storage_accounts.tfvars, modules/storage_account/diagnostics.tf, modules/storage_account/variables.tf, storage_accounts.tf
---
Currently only Storage Account diagnostic settings are supported. We need to be able to add diagnostic settings for Storage Account services such as Blob, Queue, Table, and Files
=> Support Storage Account services diagnostic settings

examples/app_gateway/302-listener-ssl-policy/agw_application.tfvars, examples/app_gateway/302-listener-ssl-policy/agw_platform.tfvars, examples/app_gateway/302-listener-ssl-policy/certificates.tfvars, examples/app_gateway/302-listener-ssl-policy/configuration.tfvars, examples/app_gateway/302-listener-ssl-policy/keyvaults.tfvars, examples/app_gateway/302-listener-ssl-policy/managed_identities.tfvars, examples/app_gateway/302-listener-ssl-policy/network_security_group_definition.tfvars, examples/app_gateway/302-listener-ssl-policy/networking.tfvars, modules/networking/application_gateway_platform/application_gateway.tf
---
Currently, there is no option of defining SSL policy for listeners by default, whether choosing from one of the predefined policies or creating a custom security policy. The PR configures a default listener SSL policy which is applied to all HTTPS listeners unless they are overridden by listener specific SSL Policy under SSL settings.
=> Add SSL policy for all HTTPS listeners by default

modules/networking/application_gateway/locals.networking.tf, modules/networking/application_gateway_platform/locals.networking.tf
---
Some params must be optional following AzureRM 2.99.0, however, they are mandatory parameters in CAF Module 5.6.1 for `azurerm_application_gateway_platform`.
Just doing a `terraform plan` using the config example [here](https://github.com/joselcaguilar/aks-baseline-automation/tree/users/joselcaguilar/tfparity/IaC/terraform)
=> Private IP address optional for App Gateway

application_gateway_platforms.tf, application_gateways.tf
---
The application gateway must wait until certificates are deployed in the Key Vault, more info added to #1374
=> Both certificates and certificate requests added as a dependency for agw

.github/workflows/standalone-scenarios.json, examples/webapps/static_site/102-static-web-app-custom-domain/configuration.tfvars, modules/webapps/static_site/custom_domain.tf, modules/webapps/static_site/output.tf, modules/webapps/static_site/variables.tf, static_sites.tf
Adding support for 'static_site_custom_domain' within 'static_site'. This is a follow up of https://github.com/aztfmod/terraform-azurerm-caf/issues/1240.
---
Adding support for "azurerm_static_site_custom_domain".
=> feat: adding support for 'static_site_custom_domain' within 'static_site' module

examples/mssql_mi/200-mi-two-regions/configuration.tfvars, examples/mssql_mi/200-mi/configuration.tfvars, msssql_managed_instances.tf
#1366 Feature request-Add support for existing azuread group for sql admins #1366
---
=> Add support for literals azuread_group_id in sql managed instances

modules/networking/application_gateway_application/http_listener.tf, modules/networking/application_gateway_application/http_settings.tf
---
- Probes must be removed before than http_settings in `modules/networking/application_gateway_application/http_settings.tf`
- Frontend ports must be removed before than listeners in `modules/networking/application_gateway_application/http_listener.tf`
It was tested [here](https://github.com/Azure/aks-baseline-automation/actions/runs/3241645514/jobs/5313865607), the error raised is described below:
```
module.caf.module.application_gateway_applications["aspnetapp_az1_agw1"].null_resource.delete_probe["probe_1"] (local-exec): ERROR: (InvalidResourceReference) Resource /subscriptions/***/resourceGroups/rg-bu0001a0008/providers/Microsoft.Network/applicationGateways/appgateway-re1-001/probes/probe-fqdn-backend-aks referenced by resource …
```
=> AGW Application dependencies issues during destroy

examples/cosmos_db/100-simple-cosmos-db-sql/sql_databases.tfvars, modules/databases/cosmos_dbs/sql_database/sql_database.tf
---
Adds support for "spatial_index" blocks and fixes creation of the following settings on the azurerm_cosmosdb_sql_container:
* unique_key block
* autoscale_settings block
* indexing_policy block
* included_path blocks
* excluded_path blocks
```
cd /tf/caf/examples
az login
terraform init
terraform plan -var-file cosmos_db/100-simple-cosmos-db-sql/sql_databases.tfvars
terraform apply -var-file cosmos_db/100-simple-cosmos-db-sql/sql_databases.tfvars
terraform destroy -var-file cosmos_db/100-simple-cosmos-db-sql/sql_databases.tfvars
```
=> Fix Cosmos DB SQL Databases module

networking_express_route.tf
changed to express_route_key from express_route.key
---
=> Invalid express_route key value

.github/workflows/standalone-scenarios.json, azurerm_application_insights.tf, examples/app_insights/103-web-test/configuration.tfvars, examples/module.tf, examples/variables.tf, locals.tf, modules/app_insights/web_test/main.tf, modules/app_insights/web_test/module.tf, modules/app_insights/web_test/output.tf, modules/app_insights/web_test/variables.tf
---
- Adding support for Application insights web test -> https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_insights_web_test
This requires https://github.com/aztfmod/terraform-provider-azurecaf/pull/211
=> add support for application_insights_web_test

modules/compute/virtual_machine/shutdown_schedule.tf
---
The current implementation is only refferencing the azurerm_linux_virtual_machine. Based on the *os_type* it 
should also consider the azurerm_*windows*_virtual_machine.
Create a Windows and Linux VM, both with shutdown schedules.
=> Fix: shutdown schedules for windows vms

examples/redis_cache/103-redis-private-endpoints/configuration.tfvars, modules/redis_cache/output.tf
---
- [] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- Remove service endpoint from redis example
- Add additional redis cache outputs
```
module.example.module.redis_caches["r1"].module.private_endpoint["pe1"].azurerm_private_endpoint.pep: Still creating... [1m0s elapsed]
module.example.module.redis_caches["r1"].module.private_endpoint["pe1"].azurerm_private_endpoint.pep: Still creating... [1m10s elapsed]
module.example.module.redis_caches["r1"].module.private_endpoint["pe1"].azurerm_private_endpoint.pep: Still creating... [1m20s elapsed]
module.example.module.redis_caches["r1"].module.private_endpoint["pe1"].azurerm_private_endpoin …
```
=> Add redis cache outputs and remove service endpoint from example

modules/compute/virtual_machine/output.tf, modules/compute/virtual_machine_scale_set/output.tf
---
Adds `identity` outputs to the vm and vmss deployments to enable RBAC/IAM configuration based on system identities.
Ran terraform validate
=> feat(compute): Add identity outputs to vm and vmss deployments

.github/workflows/standalone-scenarios.json, examples/storage_accounts/110-file-share-with-acl/configuration.tfvars, modules/storage_account/file_share/file_share.tf
---
Fix issue with the storage account file share where the module would not pick up ACL or Access Policy configuration of a file share
```
cd examples
az login
terraform init
terraform plan -var-file -var-file storage_accounts/110-file-share-with-acl/configuration.tfvars
terraform apply -var-file -var-file storage_accounts/110-file-share-with-acl/configuration.tfvars
terraform destroy -var-file -var-file storage_accounts/110-file-share-with-acl/configuration.tfvars
```
=> Fix file share ACL and Access Policy

modules/networking/application_gateway/application_gateway.tf, modules/networking/application_gateway_application/ssl_cert.tf
---
When a certificate from a keyvault is used on an App Gateway, the versionless id is used to leverage the auto-refresh of the certificate.
Reference: https://learn.microsoft.com/en-us/azure/application-gateway/key-vault-certs#supported-certificates
=>  Updated app gateway to use versionless certs from keyvault (for certs auto-refresh)

examples/apim/117-api_management_product/configuration.tfvars, examples/apim/117-api_management_product/policies/example-policy.xml, modules/apim/api_management_product/module.tf, modules/apim/api_management_product/output.tf
---
Fixes issues introduced at https://github.com/aztfmod/terraform-azurerm-caf/pull/1488:
- Policy count condition has to ensure that it is not null to create 1
- Output referencing the count with star to avoid failure if no policy is created (therefore there is no [0] element)
- New `xml_file` argument to pass the content referencing a file instead of using in two different ways the same argument
=> fix: null check, output and separate file to different key

.github/workflows/standalone-regressor-tf100.yaml, .github/workflows/standalone-tf100.yaml
Removing pipelines warnings:
- Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
- The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Removing GHA pipelines warnings

local.remote_objects.tf, locals.combined_objects.tf, modules/azuread/service_principal_password/output.tf
Add service_principal_password output to service_principal_passwords module so it could also be used by remote and dynamic secrets.
---
=> Add service_principal_password output

modules/compute/virtual_machine_scale_set/vmss_windows.tf
---
- Add missing options single_placement_group and overprovision for win vmss
=> Add single_placement_group and overprovision for win vmss

.github/workflows/standalone-scenarios.json, app_services.tf, examples/webapps/appservice/110-appservice-auth/configuration.tfvars, modules/webapps/appservice/module.tf, modules/webapps/appservice/variables.tf
To add Azure AD authentication to app service, we need to reference an existing azuread_application and service_principal_password
---
=> Add Azure AD application reference to app service authentication

modules/subscriptions/subscriptions.tf, modules/subscriptions/variables.tf, subscriptions.tf
---
We found that although tags were defined and rendered into a tags.tfvars.json file to be pickedup by the Rover, the tags were never applied to subscriptions being created. The tags however were applied as expected on other resources provisioned using this module
- Created several new subscriptions and tags were applied
-  Overloading of a global tag works as expected
- Re-applying the config on subscriptions that had no tags received the (new) tags
=> Fix subscription tagging

examples/compute/virtual_machine_scale_set/106-linux-win-vmss-lb/configurations.tfvars, modules/compute/virtual_machine_scale_set/vmss_linux.tf
- example added
- additional option to place custom_data in vmss
---
=> Enhancement: Add custom data in VMSS

diagnostics.tf, examples/storage_accounts/100-simple-storage-account-blob-container/configuration.tfvars, examples/storage_container/101-storage_container/configuration.tfvars, examples/storage_container/101-storage_container/scripts/devops_runtime_docker.sh, modules/storage_account/blob/module.tf, modules/storage_account/blob/output.tf, modules/storage_account/blob/variables.tf, modules/storage_account/container/storage_blob.tf, modules/storage_account/container/variables.tf, modules/storage_account/storage_account.tf, modules/storage_account/variables.tf, roles.tf, storage_account_blobs.tf, storage_accounts.tf, storage_container.tf, variables.tf
---
This PR is updating an end-to-end scenario on how to upload a file into a blob block or to set content of the blob using the heredoc format.
Add support in the configuration file to be relative to the var_folder_path module variable
```
rover \
-lz /tf/caf/examples \
-var-folder /tf/caf/aztfmod/examples/storage_container/101-storage_container \
-var var_folder_path="/tf/caf/aztfmod/examples/storage_container/101-storage_container" \
-tfstate example_101.tfstate \
-p ${TF_DATA_DIR}/example.tfplan -a plan
```
```
storage_account_blobs = {
devops_runtime_docker = {
storage_account_key = "sa1"
storage_container = {
key = "scripts"
}
name = "devops_runtime_docker.sh"
#
#
source = "scripts/devops_runtime_docker.sh"
delay = {
create_duration = "30s"
}
}
devops_runtime_docker_by_content = { …
```
=> Add support to upload blob content + improvements

roles.tf
Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="RoleAssignmentExists" Message="The role assignment already exists."
│ 
│   with module.caf.azurerm_role_assignment.for_deferred["managed_identities_scripts_Storage_Blob_Data_Reader_gitops"],
│   on /home/vscode/.terraform.cache/xxx/rover_jobs/20230427071036918020044/modules/caf/roles.tf line 29, in resource "azurerm_role_assignment" "for_deferred":
│   29: resource "azurerm_role_assignment" "for_deferred" {
---
=> Fix a deferred role assignment regression

azuread_credentials.tf
Add Password annotation to existing azure ad application.
---
- [X ] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [X ] I have checked to ensure there aren't other open Pull Requests for the same update/change?
- [ X ] NO
```hcl
azuread_credentials = {
level0 = {
type                          = "password"
azuread_credential_policy_key = "default_policy"
azuread_application = {
object_id = ""
application_id = ""
}
keyvaults = {
test_client = {
secret_prefix = "sp"
}
}
}
}
```
=> Adding password to existing azuread app

azuread_credentials.tf, examples/aadb2c/100-simple-aadb2c-directory/configuration.tfvars, examples/compute/kubernetes_services/104-private-cluster/aks.tfvars, examples/data_sources/100-reference-data-source/configuration.tfvars, modules/networking/application_gateway_application/ssl_cert.tf, modules/networking/private_dns_vnet_link_v1/module.tf, modules/security/keyvault_certificate/output.tf, modules/security/keyvault_certificate_request/global_sign.tf
Certificates referenced using a "key" in the configuration to create Application Gateway Listener Certificates use the versioned id.
This prevents the listener certificate from updating to the latest version of the certificate and support key rotation.
Added an output variable for the versionless_secret_id and referenced this property while creating the Application Gateway listener certificate.
---
=> Added support for version less certificate id (rotation) in App Gateway listener certificate.

examples/app_gateway/301-agw-v1/agw_application.tfvars, examples/app_gateway/302-listener-ssl-policy/agw_application.tfvars, modules/networking/application_gateway_application/scripts/set_resource.sh, modules/networking/application_gateway_application/url_path_map.tf, modules/networking/application_gateway_application/url_path_rule.tf
---
deployment fails while creating url path map.
ERROR: (ApplicationGatewayUrlPathMapMustSpecifyDefaultBackendHttpSettings) and keeps retrying till timeout.
Reason: new Azcli version makes 2 parameters mandatory in the command "az network application-gateway url-path-map create"
--default-address-pool
--default-http-settings
deployment fails while creating url path map rule fails since configuration does not provide. 
command: az network application-gateway url-path-map rule create.
reason: example configuration did not provide the below details. Worked earlier since it was not mandatory to provide the below arguments in earlier version of azcli but in the latest version of azcli, it is mandatory.
--address-pool
--http-settings
fix: updated configuration to add the http_settings_key and …
=> Fixed issues related to url path map and url path map rule creation errors

.github/workflows/standalone-scenarios.json, aks_clusters.tf, examples/compute/kubernetes_services/108-single-cluster-remote-adgroup-admin/aks.tfvars, examples/compute/kubernetes_services/108-single-cluster-remote-adgroup-admin/diagnostics.tfvars, examples/compute/kubernetes_services/108-single-cluster-remote-adgroup-admin/networking.tfvars
---
This allows you to specify an AD group from a remote landing zone as part of the `admin_groups` block in the AKS module.
Original credit to @yanndb
Run the example in `compute/kubernetes_services/108-single-cluster-remote-adgroup-admin`
=> Allow AD group in Remote LZ as AKS Cluster Admin

.github/workflows/standalone-scenarios.json, cosmos_db_roles.tf, examples/cosmos_db/100-cosmos-db-sql-role-mapping/configuration.tfvars, locals.tf, modules/databases/cosmos_dbs/output.tf, modules/databases/cosmos_dbs/sql_database.tf, modules/databases/cosmos_dbs/sql_database/output.tf, modules/roles/cosmosdb_custom_roles/main.tf, modules/roles/cosmosdb_custom_roles/module.tf, modules/roles/cosmosdb_custom_roles/output.tf, modules/roles/cosmosdb_custom_roles/variables.tf
This commit adds the following features to CAF:
* Create custom role sql definitions for Cosmos DB (var.database.cosmosdb_role_definitions)
* Create custom role sql assignments for Cosmos DB (var.database.cosmosdb_role_mapping)
---
=> Add Cosmos DB custom SQL role functionality

modules/databases/mariadb_server/server.tf
---
azurerm 3.56.0 defaults `ssl_minimal_tls_version_enforced` to "TLS1_2" causing an issue if you want values other than the default.
This PR allows you to specify other values. Possible values are [TLSEnforcementDisabled, TLS1_0, TLS1_1, and TLS1_2](https://registry.terraform.io/providers/hashicorp/azurerm/3.56.0/docs/resources/mariadb_server#ssl_minimal_tls_version_enforced).
=> Fix mariadb server minimal tls version enforced

networking_private_dns.tf
This is required when you want to link launchpad vnet to the HUB at level2 and link level2 private_dns_zones. Consider to implement vnet propagation in the same way as launchpad identities
---
=> Add support for vnet resource id in vnet link

examples/app_gateway/102-waf-policy/waf.tfvars, examples/webapps/appservice/109-appservice-appgw/waf.tfvars, modules/networking/application_gateway_waf_policies/waf_policy.tf
---
Code was ignored before.
Removing the plural fix the issue
```
...
managed_rules = {
exclusion = {
ex1 = {
match_variable          = "RequestHeaderNames"
selector                = "x-company-secret-header"
selector_match_operator = "Equals"
}
ex2 = {
match_variable          = "RequestCookieNames"
selector                = "yyy"
selector_match_operator = "EndsWith"
}
ex3 = {
match_variable          = "RequestCookieNames"
selector                = "xxx"
selector_match_operator = "StartsWith"
}
}
...
```
```
~ resource "azurerm_web_application_firewall_policy" "wafpolicy" {
id                  = "/subscriptions/xxxx/resourceGroups/rg-weu-01/providers/Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies/waf-weu-001"
name                = "waf-weu-001"
tags                = { …
```
=> Fix managed_rules exclusion

modules/networking/firewall/module.tf
---
`azurerm_firewall` forced `threat_intel_mode` to empty string if `virtual_hub` is specified. This is not required anymore in azurerm provider 3.56.0.
This PR is to allow setting the `threat_intel_mode` even if the `virtual_hub` is specified.
These changes are required in order to successfully `terraform plan` an Azure Firewall in a virtual hub. Without it we are blocked.
=> Allow threat_intel_mode in azurerm_firewall to be set when referencing a virtual_hub

modules/networking/firewall/module.tf
Related to merged PR #1673 (sorry for changing it again)
---
The previous version which failed over the value to 'Alert' can make the terraform apply fail depending on the sku_tier (will fail with Standard sku). Now the user is responsible to set the correct mode and can also omit this parameter in order to apply successfully the firewall.
terraform plan and apply of azurerm_firewall with the `virtual_hub` parameter and without the `threat_intel_mode`.
=> Allow set threat_intel_mode to be null

modules/resource_group/main.tf, modules/resource_group/module.tf, modules/resource_group/variables.tf, resource_groups.tf
---
Resource group tag overwrite is not working correctly in int-5.7.0. When global_settings_override.inherit_tags = true and global_settings_override.passthrough = true, attempting to overwrite a specific tag with a new value at the resource group level does not work. 
The original snippet of code in landingzone.tfvars
```
global_settings_override = {
default_region = "region1"
regions = {
region1 = "southeastasia"
}
passthrough = true
inherit_tags = true
}
tags = {
App         = "sampleapp"
Branch      = "dev"
Environment = "dev"
DataCenter  = "sea"
Region      = "southeastasia"
Build       = "1"
Component   = "sampleapp"
Name        = "customer-git-cs-dev-sandbox-sampleapp-sea-sit1"
Portfolio   = "customer-git-cs-dev-sandbox"
Department  = "customer-git-cs-dev"
Application = …
```
=> Updated tag inheritance logic for resource groups

examples/storage_accounts/102-storage-account-advanced-options/configuration.tfvars, modules/storage_account/storage_account.tf
---
Add sftp support on storage account
```
global_settings = {
default_region = "region1"
regions = {
region1 = "australiaeast"
}
}
resource_groups = {
test = {
name = "test"
}
}
storage_accounts = {
sa1 = {
name                     = "sa1dev"
resource_group_key       = "test"
account_kind             = "StorageV2" #Valid options are BlobStorage, BlockBlobStorage, FileStorage, Storage and StorageV2. Defaults to StorageV2
account_tier             = "Standard"  #Valid options are Standard and Premium. For BlockBlobStorage and FileStorage accounts only Premium is valid
account_replication_type = "LRS"       # https://docs.microsoft.com/en-us/azure/storage/common/storage-redundancy
min_tls_version          = "TLS1_2"    # Possible values are TLS1_0, TLS1_1, and TLS1_2. Defaults to TLS1_0 for …
```
=> Add sftp_enabled argument for storage account

virtual_machines.tf, virtual_machines_scale_sets.tf
---
To support the deployment of a VM that need to store the SSH keys in a keyvault configured with Azure AD authentication. We need to ensure the role mapping are first applied before storing the ssh keys in the keyvault secret
=> Update dependencies for role assignments

.github/workflows/standalone-networking.json, examples/networking/private_endpoint/README.md, examples/networking/private_endpoint/configuration.tfvars, modules/networking/private_endpoint/private_endpoint.tf
---
Currently, it is not possible to define a static IP-address for private endpoints by defining the `ip_configuration` block, which is supported in the [Private-Endpoint Terraform Resource >3.21.0](https://registry.terraform.io/providers/hashicorp/azurerm/3.21.0/docs/resources/private_endpoint#ip_configuration).
This PR enables reading the `ip_configuration` from the settings property.
=> Add ip_configuration block to private endpoints

modules/compute/virtual_machine/keyvault.tf
Terraform destroy failed when var.settings.keyvault.key was used instead of var.settings.keyvault_key
---
- [X ] I have checked to ensure there aren't other open Pull Requests for the same update/change?
=> Fix issue with try clause in virtual_machine module

modules/compute/aks/aks.tf
---
Reverting changes in aks `maintenance_window` dynamic block with previous `try` function.
`can` function introduces errors if value is null or not specified.
`not_allowed = null` - can function returns `true`
```
maintenance_window = {
not_allowed = null
allowed = {
day = "Saturday"
hours = [
8,
9,
10,
11,
12
]
}
}
│ Error: Attempt to get attribute from null value
│ 
│   on .terraform/modules/caf/modules/compute/aks/aks.tf line 312, in resource "azurerm_kubernetes_cluster" "aks":
│  312:           end   = var.settings.maintenance_window.not_allowed.end
│     ├────────────────
│     │ var.settings.maintenance_window.not_allowed is null
│ 
│ This value is null, so it does not have any attributes.
╵
╷
│ Error: Attempt to get attribute from null value
│ 
│   on …
```
=> Revert AKS maintenance window settings

modules/compute/virtual_machine_extensions/custom_script.tf
---
Currently, we look for the custom script filepath inside the current landingzone first, so if we try to access a remote storage account with the same key as a local storage account, it will get ignored and the local one is picked. This PR puts the remote storage first.
=> Fixed custom script location priority (remote must be first)

modules/compute/virtual_machine/shutdown_schedule.tf
webhook_url logic make the variable required, should not be required in tfvars.
---
=> Fix webhook_url logic, variable should not be required

modules/azuread/applications/module.tf
---
azuread_service_principal  does not have owners argument defined. It can't rotate (delete and create) credentials as the user/identity created the SPN does not have ownership of that and if try to add that (ownership) manually it would delete that in the next run.
The password rotation works if use Application Administrator privileges which obviously is not according to least privilege model.
=> Added owners argument for spn

examples/storage_container/101-storage_container/configuration.tfvars, modules/storage_account/blob/module.tf
---
azurerm_storage_blob creation was failing, when var_folder_path is set to "" ( which is the default )
Splitting up the file checks for var_folder_path and without var_folder_path. Checking for the existence of a file using var.var_folder_path/var.settings.source, otherwise using var.settings.source if set.
Removed fileexists check from source_content, as source_content is not meant to hold a file system path.
=> fix: source and source_content parsing

modules/databases/mssql_managed_database_v1/var/settings/srtdays.tf, modules/databases/mssql_managed_instance/managed_instance.tf
```hcl
resource "azurerm_resource_group_template_deployment" "mssqlmi" {
~ id                  = "/subscriptions/xxxx/resourceGroups/yyyy/providers/Microsoft.Resources/deployments/sql-prd02" -> (known after apply)
~ name                = "sql-prd02" -> "mssqlmi" # forces replacement
```
This PR addresses a regression that was forcing the SQL MI to be destroyed and recreated
It was also preventing multiple SQL mi instances to be deployed in the same resource group.
It also fixes in the SQL MI V1 a condition when short_term_retention_days is not set in the configuration file to create a SQL MI Database (V1)
=> Fix SQL MI regressions

modules/azuread/applications/module.tf, modules/azuread/credentials/password.tf, modules/azuread/service_principal_password/module.tf
---
- [x ] I have checked to ensure there aren't other open Pull Requests for the same update/change?
When renaming an existing NSG that is already associated with a subnet, the results of the apply shows creating first before destroying when the correct behavior is to destroy then create. This results in the apply failing with the error that complains that the subnet already exists and needs to be imported into Terraform for management.
aztfmod version is int-5.7.0 and terraform version is 1.4.6
```
│ Error: A resource with the ID "/subscriptions/xxxxx/resourceGroups/exampleRG1/providers/Microsoft.Network/virtualNetworks/xxxxx/subnets/xxxxxx" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for …
```
=> Create before destroy for azuread

modules/compute/aks/aks.tf
---
Oms add-on didn't work anymore. This part of the code was duplicated in the try block.
```
for_each = try(var.settings.oms_agent[*], var.settings.oms_agent[*], {})
```
=> Fix OMS add-on for AKS

modules/compute/virtual_machine/vm_linux.tf, modules/compute/virtual_machine/vm_windows.tf
Add secure_boot_enabled and vtpm_enabled options in Windows and Linux VMs
Create a VM with the options enabled like:
```terraform
global_settings = {
default_region = "region1"
regions = {
region1 = "westeurope"
}
}
resource_groups = {
vm_region1 = {
name = "example-virtual-machine-olandese"
}
}
virtual_machines = {
domain_controller_1_vm = {
resource_group = {
key = "vm_region1"
}
provision_vm_agent                   = true
boot_diagnostics_storage_account_key = ""
os_type                              = "windows"
keyvault_key = "example_vm_rg1"
networking_interfaces = {
nic0 = {
vnet_key                = "vnet_region1"
subnet_key              = "example"
name                    = "0"
enable_ip_forwarding    = false
internal_dns_name_label = "nic0"
}
}
data_disks = {
vm-wl-addc-datadisk = …
```
=> Add secure_boot_enabled and vtpm_enabled options

modules/roles/custom_roles/module.tf
We have a customer requirement to be able to create custom roles with specific names, not following the solution naming convention. Magnus Implemented standardized solution for global settings override.
custom_role don't have the settings var, but existing custom_role var represent the same (each.value).
---
=> Blinq global settings override custom role

keyvault_certificate_requests.tf, modules/security/keyvault_certificate_request/global_sign.tf, modules/security/keyvault_certificate_request/output.tf, modules/security/keyvault_certificate_request/variables.tf
---
Code
```
keyvault_certificate_requests = {
csr0 = {
name         = "csr-with-globalsign"
lz_key       = "cert_lz"
keyvault_key = "cert_kv"
cert_password_key = "kv-issuer-password-key"
cert_secret_name  = "kv-issuer-password" # reference to keyvault secrets name 
certificate_policy = {
issuer_key_or_name  = "cert_kv_issuer_0"
exportable          = true
key_size            = 4096 // value can be 2048, 3072 or 4096
key_type            = "RSA"
reuse_key           = false
renewal_action      = "AutoRenew"
lifetime_percentage = 90
content_type = "application/x-pkcs12" // application/x-pem-file
x509_certificate_properties = {
subject            = "CN=yourdomaingoeshere"
validity_in_months = 1
key_usage          = ["keyCertSign"]
subject_alternative_names = {
dns_names = []
emails    = [] …
```
=> Fix the keyvault request that gets password from keyvault by using valid uri 

.github/workflows/standalone-scenarios-longrunners.json, examples/networking/virtual_wan/110-vwan-hub-gw-p2s-keyvault-cert/virtual_wan.tfvars, modules/networking/virtual_wan/variables.tf, modules/networking/virtual_wan/virtual_hub/point_to_site_gateway.tf, modules/networking/virtual_wan/virtual_hub/variables.tf, modules/networking/virtual_wan/virtual_wan.tf, networking_virtual_hubs.tf, networking_virtual_wan.tf
=> feat(virtual_hubs): p2s_config keyvault secret

keyvault_certificate_requests.tf, roles.tf
---
```
role_mapping = {
built_in_role_mapping = {
servicebus_topics = {
"topic" = {
"Azure Service Bus Data Sender" = {
azuread_groups = {
keys = ["group"]
}
}
}
} 
}
}
```
=> Add servicebus_topics scope for role assignment

modules/roles/custom_roles/module.tf
If you try to create a custom role definition (following the examples) you get the following error: 
This fixes the need to add an empty custom_role.global_settings variable to make it work.
To see the error: 
Run the example in the folder azuread/101-custom-role-assignable-scopes
=> Fix error with missing global settings in variable

modules/networking/public_ip_addresses/variables.tf
---
reverse_fqdn requires a string to be defined for public_ip_address, but was bool, which made it unusable
=> fix(public_ip_addresses): reverse_fqdn type

modules/networking/private_endpoint/private_endpoint.tf
This feature will allow to create a delay or wait time after Private Endpoint creation if needed. This delay will help azure policy related to private dns zone to take effect (linking Azure private dns zone to private endpoint). This feature will work only if the variable **var.settings.delay_time_after_creation** is used in the private endpoint deployment.
To test this feature, use the parameter **delay_time_after_creation** in private_endpoints variable for a particular resource.
=> Add wait time/delay  feature after private endpoint creation for private DNS zone policy

examples/identity/active_directory_domain_service/100-active_directory_domain_service-replica/configuration.tfvars, modules/identity/active_directory_domain_service/module.tf
---
Add support of [domain_configuration_type] (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/active_directory_domain_service#domain_configuration_type) in the AADDS module.
Edit example configuration by adding the [domain_configuration_type] with "FullySynced"
=> Add Support of domain_configuration_type parameter

examples/compute/kubernetes_services/101-single-cluster/aks.tfvars, modules/compute/aks/aks.tf
Note: There already is a PR #1820 which doesn't look to be ready for merging and is stale since October, thus creating this PR
---
This adds temporary_name_for_rotation to aks default node pool configuration.
=> feat(aks): add temporary_name_for_rotation

modules/networking/application_gateway_application/scripts/set_resource.sh
Fixed typo on set_resource.sh - line 238
---
- [ x] I have checked to ensure there aren't other open Pull Requests for the same update/change?
release 5.7.8 has a typo on line 238 of set_resource.sh
- [x ] NO
=> Fixed typo on set_resource.sh

.github/workflows/standalone-networking.json, .github/workflows/standalone-scenarios-longrunners.json, examples/module.tf, examples/networking/virtual_wan/111-vwan-vpn-gateway-connection-with-nat/virtual_wan.tfvars, examples/variables.tf, local.remote_objects.tf, locals.combined_objects.tf, locals.tf, modules/networking/virtual_wan/virtual_hub/site_to_site_gateway.tf, modules/networking/vpn_gateway_connection/module.tf, modules/networking/vpn_gateway_nat_rule/main.tf, modules/networking/vpn_gateway_nat_rule/module.tf, modules/networking/vpn_gateway_nat_rule/output.tf, modules/networking/vpn_gateway_nat_rule/variables.tf, networking_vpn_gateway_connection.tf, networking_vpn_gateway_nat_rule.tf, recovery_vaults.tf
---
This feature was missing from VPN Gateway Connection. Adding this will allow using CAF module to provision NAT rules and attach them to VPN Gateway Connection in order to solve IP address range overlapping.
Run `111-vwan-vpn-gateway-connection-with-nat` example.
=> Add VPN Gateway NAT Rules module

modules/data_factory/data_factory/module.tf
global_parameter should be processed as list of objects
---
global_parameter is not treated correctly in the current code, resulting in an incorrect code generation and even errors.
The proposed fix solves this issue.
- [X ] NO
Created a data factory with 2 global parameters as follows which tested OK:
data_factory = {
data_factory = {
df_adf = {
name = "adf"
resource_group = {
key = "rg_adf"
#name = ""
}
global_parameter = {
gp_p1 = {
name  = "P1"
type  = "String"
value = "p1"
} 
gp_p2 = {
name  = "P2"
type  = "String"
value = "p2"
} 
}
identity = {
type = "SystemAssigned"
}
managed_virtual_network_enabled = false
}
=> Fix: Data factory iteration for global_parameter

.github/workflows/standalone-scenarios-longrunners.json, api_management.tf, examples/apim/118-api_management_platform_stv2/configuration.tfvars, modules/apim/api_management/module.tf, modules/apim/api_management/variables.tf
@mark-gronow, I've updated #1960 in this one.
Here's a summary of the most important changes:
* [`.github/workflows/standalone-scenarios-longrunners.json`](diffhunk://#diff-b150a39b5154fd43a63637cdf503405d6c767eb1b65e31ffda3db0fa84a69011R20): Added `apim/118-api_management_platform_stv2` to the list of standalone scenarios long runners.
* [`examples/apim/118-api_management_platform_stv2/configuration.tfvars`](diffhunk://#diff-b3a1beee263f0137e32156fefd8b17e44badeab5ebc718f0334c427015237c16R1-R181): Added a new configuration file for the `apim/118-api_management_platform_stv2` platform. This includes settings for global settings, resource groups, vnets, network security group definition, public IP addresses, API management, and managed identities.
* …
=> APIM - use existing pip - #1960

.github/workflows/on_push_fmt.yaml
This pull request introduces a new GitHub workflow in the `.github/workflows/on_push_fmt.yaml` file. The workflow, named `Terraform Format`, is triggered on push events to the `main` branch. It sets up a job that checks out the code, sets up Terraform, applies the `terraform fmt -recursive` command to format the Terraform code, commits any changes resulting from the formatting, and finally pushes these changes back to the repository.
=> Adding FMT on push

.devcontainer/docker-compose.yml, .github/workflows/landingzone-scenarios.yaml, .github/workflows/rover.yaml, .github/workflows/standalone-compute.yaml, .github/workflows/standalone-networking.yaml, .github/workflows/standalone-regressor-tf100.yaml, .github/workflows/standalone-tf100.yaml
This pull request primarily updates the version of the `aztfmod/rover` Docker image used across multiple files in the project. The version is updated from `1.7.5-2405.0203` to `1.8.4-2405.2306`. This change affects the project's development environment setup and the execution environment for various GitHub workflows.
Expected improvement: Terraform 1.8.4 performance improvement at ```plan``` time.
=> Upgrade to TF 1.8.4

.github/dependabot.yaml
This pull request includes the addition of a `dependabot.yaml` configuration file in the `.github` directory. This file specifies that Dependabot should check for updates to the GitHub Actions, devcontainers, and Terraform package ecosystems on a weekly basis. 
* [`.github/dependabot.yaml`](diffhunk://#diff-ee0c08340ace9ac3ce3c78e2377968bca2376b8bfd9a7a48d96515f5490a902cR1-R19): Added a new configuration file for Dependabot. This file instructs Dependabot to check for updates in the "github-actions", "devcontainers", and "terraform" package ecosystems weekly.
=> Adding dependabot configuration

.github/workflows/standalone-scenarios-additional.json, cognitive_service.tf, examples/cognitive_services/101-cognitive-services-account-managed-identity/configuration.tfvars, modules/cognitive_services/cognitive_services_account/cognitive_service_account.tf, modules/cognitive_services/cognitive_services_account/main.tf, modules/cognitive_services/cognitive_services_account/output.tf, modules/cognitive_services/cognitive_services_account/variables.tf
---
Added identity assignment to cognitive services.
Added Public network access.
Added Support for base tags
=> Feat: Enhancement cognitive services

.github/workflows/standalone-scenarios.json, examples/storage_accounts/112-storage-account-with-defender/configuration.tfvars, modules/storage_account/storage_defender.tf
---
Add support for enabling Defender for Storage on a storage account.
=> Add storage defender support

modules/messaging/web_pubsub/private_endpoint.tf
---
We are getting following error message when using private endpoints with webpubsub:
2024/07/29 06:57:53 Error: Inconsistent conditional result types 2024/07/29 06:57:53
2024/07/29 06:57:53   on /home/AzDevOps_azpcontainer/.terraform/modules/stage2/modules/messaging/web_pubsub/private_endpoint.tf line 11, in module "private_endpoint":
2024/07/29 06:57:53   11:   private_dns     = can(each.value.private_dns) ? var.remote_objects.private_dns : {}
2024/07/29 06:57:53     ├────────────────
2024/07/29 06:57:53     │ each.value.private_dns is object with 2 attributes
2024/07/29 06:57:53     │ var.remote_objects.private_dns is object with 5 attributes
2024/07/29 06:57:53
2024/07/29 06:57:53 The true and false result expressions must have consistent types. The 'true'
2024/07/29 06:57:53 value …
=> fix: inconsistent types in conditional

examples/cognitive_services/101-cognitive-services-account-managed-identity/configuration.tfvars, examples/mysql_flexible_server/103-mysql-flexible-private-endpoint/configuration.tfvars, modules/databases/mysql_flexible_server/main.tf, modules/databases/mysql_flexible_server/private_endpoints.tf, modules/databases/mysql_flexible_server/variables.tf, mysql_flexible_servers.tf
Address the issue -  https://github.com/aztfmod/terraform-azurerm-caf/issues/2048
---
- [ x] I have added example(s) inside the [./examples/] folder
- [x ] I have checked to ensure there aren't other open Pull Requests for the same update/change?
- [x ] NO
Refer to https://github.com/chianw/aztfmod-mysql-flexible-server for example of testing this
=> Add private endpoint support for mysql flexible server

examples/azuread/107-azuread-application-with-single-page-application/configuration.tfvars, modules/azuread/applications_v1/azuread_application.tf
=> feat(azuread_application): random id for oauth2_permission_scope

modules/databases/cosmos_dbs/cosmosdb_account.tf
---
This pull request includes changes to the `modules/databases/cosmos_dbs/cosmosdb_account.tf` file to add dynamic backup configurations for Cosmos DB accounts.
Key changes:
* Added a dynamic block for `backup` configurations in the `azurerm_cosmosdb_account` resource. This block includes parameters such as `type`, `tier`, `interval_in_minutes`, `retention_in_hours`, and `storage_redundancy`, which are conditionally set based on the `var.settings.backup` variable.
* Removed unnecessary blank lines at the end of the `azurerm_cosmosdb_account` resource definition.
=> added backup in azurerm_cosmosdb_account

modules/compute/aks/aks.tf
---
The current module has a bug if values for `upgrade_settings` are set
```
│ Error: Unsupported attribute
│ 
│   on .terraform/modules/caf/modules/compute/aks/aks.tf line 80, in resource "azurerm_kubernetes_cluster" "aks":
│   80:         max_surge = upgrade_settings.value.max_surge
│     ├────────────────
│     │ upgrade_settings.value is 1
│ 
│ Can't access attributes on a primitive-typed value (number).
```
I'm also adding the optional settings in the [upgrade_settings](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#max_surge) block
=> AKS: Fix default nodepool upgrade settings

modules/webapps/function_app/module.tf
---
There is currently configurations missing for IP Restriction rules that exist for the SCM IP Restriction Rules, as a result we see an error that gets thrown via Terraform and an apply cannot be done.
```
2025-02-14T15:45:13.5562971Z Error: expanding `site_config` for Function App "APP" (Resource Group "rg"): one of `ip_address`, `service_tag` or `virtual_network_subnet_id` must be set for an IP restriction
2025-02-14T15:45:13.5563279Z 
2025-02-14T15:45:13.5563615Z   with module.caf.module.function_apps["APP"].azurerm_function_app.function_app,
2025-02-14T15:45:13.5564133Z   on .terraform/modules/caf/modules/webapps/function_app/module.tf line 12, in resource "azurerm_function_app" "function_app":
2025-02-14T15:45:13.5564754Z   12: resource "azurerm_function_app" "function_app" {
```
=> FIX: Missing Parameters in Function App result in failed execution

modules/monitoring/monitor_activity_log_alert/module.tf
---
monitor_activity_log_alert resource definition has duplicate lz_key in the resource references.
=> fix: duplicate lz key reference
